#!/usr/bin/python
# coding=ANSI

Celldata = {"Abaelun Mine":"Abaelun-Mine",
"Abaesen-Pulu Egg Mine":"Abaesen-Pulu, Eiermine",
"Abanabi":"Abanabi",
"Abandoned Shipwreck, Cabin":"Verlassenes Schiffswrack, Kabine",
"Abandoned Shipwreck, Lower Level":"Verlassenes Schiffswrack, Unterdeck",
"Abandoned Shipwreck, Upper Level":"Verlassenes Schiffswrack, Oberdeck",
"Abebaal Egg Mine":"Abebaal, Eiermine",
"Abernanit":"Abernanit",
"Abinabi":"Abinabi",
"Adanumuran":"Adanumuran",
"Addadshashanammu, Shrine":"Addadshashanammu, Schrein",
"Addamasartus":"Addamasartus",
"Ahallaraddon Egg Mine":"Ahallaraddon, Eiermine",
"Ahanibi-Malmus Egg Mine":"Ahanibi-Malmus, Eiermine",
"Aharasaplit Camp, Zallay's Yurt":"Aharasaplit-Lager, Zallays Zelt",
"Aharnabi":"Aharnabi",
"Aharunartus":"Aharunartus",
"Ahemmusa Camp":"Ahemmusa-Lager",
"Ahemmusa Camp, Addammus's Yurt":"Ahemmusa-Lager, Addammus' Zelt",
"Ahemmusa Camp, Ashkhan's Yurt":"Ahemmusa-Lager, Zelt des Ashkhan",
"Ahemmusa Camp, Assamma-Idan's Yurt":"Ahemmusa-Lager, Assamma-Idans Zelt",
"Ahemmusa Camp, Dutadalk's Yurt":"Ahemmusa-Lager, Dutadalks Zelt",
"Ahemmusa Camp, Kausi's Yurt":"Ahemmusa-Lager, Kausis Zelt",
"Ahemmusa Camp, Lanabi's Yurt":"Ahemmusa-Lager, Lanabis Zelt",
"Ahemmusa Camp, Mamaea's Yurt":"Ahemmusa-Lager, Mamaeas Zelt",
"Ahemmusa Camp, Nummu's Yurt":"Ahemmusa-Lager, Nummus Zelt",
"Ahemmusa Camp, Wise Woman's Yurt":"Ahemmusa-Lager, Zelt der Weisen Frau",
"Ahinipalit":"Ahinipalit",
"Aidanat Camp, Abassel's Yurt":"Aidanat-Lager, Abassels Zelt",
"Ainab":"Ainab",
"Ainab, Shrine":"Ainab, Schrein",
"Ainat":"Ainat",
"Akimaes Grotto":"Akimaes-Grotte",
"Akimaes-Ilanipu Egg Mine":"Akimaes-Ilanipu, Eiermine",
"Akulakhan's Chamber":"Akulakhans Kammer",
"Alas Ancestral Tomb":"Alas-Ahnengruft",
"Ald Daedroth":"Ald Daedroth",
"Ald Daedroth, Antechamber":"Ald Daedroth, Vorraum",
"Ald Daedroth, Inner Shrine":"Ald Daedroth, Innerer Schrein",
"Ald Daedroth, Left Wing":"Ald Daedroth, Linker Flügel",
"Ald Daedroth, Outer Shrine":"Ald Daedroth, Äußerer Schrein",
"Ald Daedroth, Right Wing":"Ald Daedroth, Rechter Flügel",
"Ald Redaynia":"Ald Redaynia",
"Ald Redaynia, Tower":"Ald Redaynia, Turm",
"Ald Sotha":"Ald Sotha",
"Ald Sotha, Lower Level":"Ald Sotha, Untere Ebene",
"Ald Sotha, Shrine":"Ald Sotha, Schrein",
"Ald Sotha, Upper Level":"Ald Sotha, Obere Ebene",
"Ald Velothi":"Ald Velothi",
"Ald Velothi, Fevila Bethrano's Shack":"Ald Velothi, Fevila Bethranos Hütte",
"Ald Velothi, Ganus Lloryn's Shack":"Ald Velothi, Ganus Lloryns Hütte",
"Ald Velothi, Ienas Arvel's Shack":"Ald Velothi, Ienas Arvels Hütte",
"Ald Velothi, Lledsea Relas's Shack":"Ald Velothi, Lledsea Relas' Hütte",
"Ald Velothi, Llerar Vinden's Shack":"Ald Velothi, Llerar Vindens Hütte",
"Ald Velothi, Outpost":"Ald Velothi, Außenposten",
"Ald Velothi, Sathas Rivul's Shack":"Ald Velothi, Sathas Rivuls Hütte",
"Ald Velothi, Vireveri Darethran's Shack":"Ald Velothi, Vireveri Darethrans Hütte",
"Ald-ruhn":"Ald'ruhn",
"Ald-ruhn, Ald Skar Inn":"Ald'ruhn, Taverne Ald Skar",
"Ald-ruhn, Arobar Guard Quarters":"Ald'ruhn, Arobar-Wachquartiere",
"Ald-ruhn, Arobar Manor Bedrooms":"Ald'ruhn, Haus Arobar",
"Ald-ruhn, Arobar Manor Entrance":"Ald'ruhn, Eingang zum Haus Arobar",
"Ald-ruhn, Arobar Private Quarters":"Ald'ruhn, Arobar, Privatquartiere",
"Ald-ruhn, Aryni Orethi's House":"Ald'ruhn, Aryni Orethis Haus",
"Ald-ruhn, Bevene Releth: Clothier":"Ald'ruhn, Bevene Releth: Schneiderin",
"Ald-ruhn, Bivale Teneran: Clothier":"Ald'ruhn, Bivale Teneran: Schneiderin",
"Ald-ruhn, Boldrisa Andrano's House":"Ald'ruhn, Boldrisa Andranos Haus",
"Ald-ruhn, Braynas Hlervu's House":"Ald'ruhn, Braynas Hlervus Haus",
"Ald-ruhn, Cienne Sintieve: Alchemist":"Ald'ruhn, Cienne Sintieve: Alchemistin",
"Ald-ruhn, Codus Callonus: Bookseller":"Ald'ruhn, Codus Callonus: Buchhändler",
"Ald-ruhn, Council Club":"Ald'ruhn, Ratstaverne",
"Ald-ruhn, Council Hostel":"Ald'ruhn, Ratsherberge",
"Ald-ruhn, Dandera Selaro: Smith":"Ald'ruhn, Dandera Selaro: Schmiedin",
"Ald-ruhn, Daynes Redothril: Pawnbroker":"Ald'ruhn, Daynes Redothril: Pfandleiher",
"Ald-ruhn, Dravasa Andrethi's House":"Ald'ruhn, Dravasa Andrethis Haus",
"Ald-ruhn, Drinar Varyon's House":"Ald'ruhn, Drinar Varyons Haus",
"Ald-ruhn, Galsa Gindu's House":"Ald'ruhn, Galsa Gindus Haus",
"Ald-ruhn, Galthragoth's House":"Ald'ruhn, Galthragoths Haus",
"Ald-ruhn, Gildan's House":"Ald'ruhn, Gildans Haus",
"Ald-ruhn, Gindrala Hleran's House":"Ald'ruhn, Gindrala Hlerans Haus",
"Ald-ruhn, Goras Andrelo's House":"Ald'ruhn, Goras Andrelos Haus",
"Ald-ruhn, Guard Tower 1":"Ald'ruhn, Wachturm 1",
"Ald-ruhn, Guard Tower 2":"Ald'ruhn, Wachturm 2",
"Ald-ruhn, Guild of Fighters":"Ald'ruhn, Kriegergilde",
"Ald-ruhn, Guild of Mages":"Ald'ruhn, Magiergilde",
"Ald-ruhn, Guls Llervu's House":"Ald'ruhn, Guls Llervus Haus",
"Ald-ruhn, Hanarai Assutlanipal's House":"Ald'ruhn, Hanarai Assutlanipals Haus",
"Ald-ruhn, Ienas Sarandas's House":"Ald'ruhn, Ienas Sarandas' Haus",
"Ald-ruhn, Ilmiril's House":"Ald'ruhn, Ilmirils Haus",
"Ald-ruhn, Llether Vari: Enchanter":"Ald'ruhn, Llether Vari: Verzauberungen",
"Ald-ruhn, Llethri Guard Quarters":"Ald'ruhn, Llethri Wachquartiere",
"Ald-ruhn, Llethri Manor Bedrooms":"Ald'ruhn, Haus Llethri",
"Ald-ruhn, Llethri Manor Entrance":"Ald'ruhn, Eingang zum Haus Llethri",
"Ald-ruhn, Llethri Private Quarters":"Ald'ruhn, Llethri, Privatquartiere",
"Ald-ruhn, Malpenix Blonia: Trader":"Ald'ruhn, Malpenix Blonia: Händler",
"Ald-ruhn, Manor District":"Ald'ruhn, Manor-Distrikt",
"Ald-ruhn, Morag Tong Guildhall":"Ald'ruhn, Gildehalle der Morag Tong ",
"Ald-ruhn, Morvayn Quarters":"Ald'ruhn, Morvayn-Quartiere",
"Ald-ruhn, Pellecia Aurrus's House":"Ald'ruhn, Pellecia Aurrus' Haus",
"Ald-ruhn, Practice Room":"Ald'ruhn, Übungsraum",
"Ald-ruhn, Ramoran Manor":"Ald'ruhn, Haus Ramoran",
"Ald-ruhn, Ramoran Private Quarters":"Ald'ruhn, Ramoran, Privatquartiere",
"Ald-ruhn, Redoran Council Entrance":"Ald'ruhn, Zugang zum Redoranischen Rat",
"Ald-ruhn, Redoran Council Hall":"Ald'ruhn, Redoranische Ratshalle",
"Ald-ruhn, Sarethi Guard Quarters":"Ald'ruhn, Sarethi-Wachquartiere",
"Ald-ruhn, Sarethi Manor":"Ald'ruhn, Haus Sarethi",
"Ald-ruhn, Tauryon's House":"Ald'ruhn, Tauryons Haus",
"Ald-ruhn, Temple":"Ald'ruhn, Tempel",
"Ald-ruhn, The Rat In The Pot":"Ald'ruhn, Die Ratte und der Topf",
"Ald-ruhn, Tiras Sadus: General Merchandise":"Ald'ruhn, Tiras Sadus: Händler",
"Ald-ruhn, Tuveso Beleth: Smith":"Ald'ruhn, Tuveso Beleth: Schmiedin",
"Ald-ruhn, Venim Manor Bedrooms":"Ald'ruhn, Haus Venim",
"Ald-ruhn, Venim Manor Entrance":"Ald'ruhn, Eingang zum Haus Venim",
"Ald-ruhn, Venim Manor Guard Quarters":"Ald'ruhn, Venim-Wachquartiere",
"Ald-ruhn, Venim Manor Private Quarters":"Ald'ruhn, Haus Venim, Privatquartiere",
"Ald-ruhn, Venim Manor Right Wing":"Ald'ruhn, Haus Venim, rechter Flügel",
"Aleft":"Aleft",
"Alen Ancestral Tomb":"Alen-Ahnengruft",
"Almurbalarammi, Shrine":"Almurbalarammi, Schrein",
"Alof's Farmhouse":"Alofs Bauernhaus",
"An Abandoned Shack":"Eine verlassene Hütte",
"Ancient Shipwreck, Cabin":"Altes Schiffswrack, Kabine",
"Ancient Shipwreck, Lower Level":"Altes Schiffswrack, Unterdeck",
"Ancient Shipwreck, Upper Level":"Altes Schiffswrack, Oberdeck",
"Andalen Ancestral Tomb":"Andalen-Ahnengruft",
"Andalor Ancestral Tomb":"Andalor-Ahnengruft",
"Andas Ancestral Tomb":"Andas-Ahnengruft",
"Andasreth":"Andasreth",
"Andasreth, Lower Level":"Andasreth, Untere Ebene",
"Andasreth, Propylon Chamber":"Andasreth, Propylon-Kammer",
"Andasreth, Upper Level":"Andasreth, Obere Ebene",
"Andavel Ancestral Tomb":"Andavel-Ahnengruft",
"Andrano Ancestral Tomb":"Andrano-Ahnengruft",
"Andrethi Ancestral Tomb":"Andrethi-Ahnengruft",
"Andules Ancestral Tomb":"Andules-Ahnengruft",
"Ansi":"Ansi",
"Aralen Ancestral Tomb":"Aralen-Ahnengruft",
"Aran Ancestral Tomb":"Aran-Ahnengruft",
"Arano Ancestral Tomb":"Arano-Ahnengruft",
"Arano Plantation":"Arano-Plantage",
"Arenim Ancestral Tomb":"Arenim-Ahnengruft",
"Arethan Ancestral Tomb":"Arethan-Ahnengruft",
"Arkngthand, Cells of Hollow Hand":"Arkngthand, Zellen der Hohlen Hand",
"Arkngthand, Deep Ore Passage":"Arkngthand, Tiefe Erzpassage",
"Arkngthand, Hall of Centrifuge":"Arkngthand, Halle der Zentrifuge",
"Arkngthand, Heaven's Gallery":"Arkngthand, Himmelsgalerie",
"Arkngthand, Land's Blood Gallery":"Arkngthand, Landblutgalerie",
"Arkngthand, Weepingbell Hall":"Arkngthand, Klageläuten-Halle",
"Arkngthunch-Sturdumz":"Arkngthunch-Sturdumz",
"Arrow, Cabin":"Schneller Pfeil, Kabine",
"Arrow, Lower Level":"Schneller Pfeil, Unterdeck",
"Arrow, Upper Level":"Schneller Pfeil, Oberdeck",
"Arvel Manor":"Haus Arvel",
"Arvel Manor, Slave Shack":"Haus Arvel, Sklavenhütte",
"Arvel Manor, Slavemaster's Shack":"Haus Arvel, Hütte des Sklavenaufsehers",
"Arvel Manor, Storage Shack":"Haus Arvel, Lagerhütte",
"Arvel Plantation":"Arvel-Plantage",
"Aryon Ancestral Tomb":"Aryon-Ahnengruft",
"Arys Ancestral Tomb":"Arys-Ahnengruft",
"Asha-Ahhe Egg Mine":"Asha-Ahhe, Eiermine",
"Ashalmawia":"Ashalmawia",
"Ashalmawia, Shrine":"Ashalmawia, Schrein",
"Ashalmawia, Shrine, Sunken Vaults":"Ashalmawia, Schrein, Versunkene Gewölbe",
"Ashalmimilkala, Shrine":"Ashalmimilkala, Schrein",
"Ashamanu Camp, Kausha's Yurt":"Ashamanu-Lager, Kaushas Zelt",
"Ashanammu":"Ashanammu",
"Ashimanu Egg Mine":"Ashimanu, Eiermine",
"Ashimanu Egg Mine, Queen's Lair":"Ashimanu, Eiermine, Nest der Königin",
"Ashinabi":"Ashinabi",
"Ashinabi, Smuggler Den":"Ashinabi, Schmugglerhöhle",
"Ashirbadon":"Ashirbadon",
"Ashir-Dan":"Ashir-Dan",
"Ashmelech":"Ashmelech",
"Ashunartes, Shrine":"Ashunartes, Schrein",
"Ashurnabitashpi":"Ashurnabitashpi",
"Ashurnibibi":"Ashurnibibi",
"Ashurnibibi, Shrine":"Ashurnibibi, Schrein",
"Assalkushalit, Shrine":"Assalkushalit, Schrein",
"Assarnatamat, Shrine":"Assarnatamat, Schrein",
"Assarnud":"Assarnud",
"Assemanu":"Assemanu",
"Assemanu, Shrine":"Assemanu, Schrein",
"Assernerairan, Shrine":"Assernerairan, Schrein",
"Assu":"Assu",
"Assumanu":"Assumanu",
"Assurdirapal, Inner Shrine":"Assurdirapal, Innerer Schrein",
"Assurdirapal, Shrine":"Assurdirapal, Schrein",
"Assurnabitashpi":"Assurnabitashpi",
"Assurnabitashpi, Shrine":"Assurnabitashpi, Schrein",
"Bal Fell":"Bal Fell",
"Bal Fell, East Wing":"Bal Fell, Östlicher Flügel",
"Bal Fell, Inner Shrine":"Bal Fell, Innerer Schrein",
"Bal Fell, Outer Shrine":"Bal Fell, Äußerer Schrein",
"Bal Fell, West Wing":"Bal Fell, Westlicher Flügel",
"Bal Isra":"Bal Isra",
"Bal Ur":"Bal Ur",
"Bal Ur, Shrine":"Bal Ur, Schrein",
"Bal Ur, Underground":"Bal Ur, Untergrund",
"Balmora":"Balmora",
"Balmora, Astius Hanotepelus' House":"Balmora, Astius Hanotepelus' Haus",
"Balmora, Balyn Omarel's House":"Balmora, Balyn Omarels Haus",
"Balmora, Caius Cosades' House":"Balmora, Caius Cosades’ Haus",
"Balmora, Clagius Clanler: Outfitter":"Balmora, Clagius Clanler: Händler",
"Balmora, Council Club":"Balmora, Ratstaverne",
"Balmora, Dorisa Darvel: Bookseller":"Balmora, Dorisa Darvel: Buchhändlerin",
"Balmora, Dralasa Nithryon: Pawnbroker":"Balmora, Dralasa Nithryon: Pfandleiherin",
"Balmora, Dralcea Arethi's House":"Balmora, Dralcea Arethis Haus",
"Balmora, Dralosa Athren's House":"Balmora, Dralosa Athrens Haus",
"Balmora, Drarayne Thelas' House":"Balmora, Drarayne Thelas Haus",
"Balmora, Drarayne Thelas' Storage":"Balmora, Drarayne Thelas Lager",
"Balmora, Dura gra-Bol's House":"Balmora, Dura gra-Bol's Haus",
"Balmora, Eastern Guard Tower":"Balmora, Östlicher Wachturm",
"Balmora, Eight Plates":"Balmora, Acht Teller",
"Balmora, Fast Eddie's House":"Balmora, Flinkfinger-Eddis Haus",
"Balmora, Guild of Fighters":"Balmora, Kriegergilde",
"Balmora, Guild of Mages":"Balmora, Magiergilde",
"Balmora, Hecerinde's House":"Balmora, Hecerindes Haus",
"Balmora, Hlaalo Manor":"Balmora, Haus Hlaalo",
"Balmora, Hlaalu Council Manor":"Balmora, Haus des Hlaalu-Rates",
"Balmora, Itan's House":"Balmora, Itans Haus",
"Balmora, Karlirah's House":"Balmora, Karlirahs Haus",
"Balmora, Lucky Lockup":"Balmora, Zum Glückspilz",
"Balmora, Meldor: Armorer":"Balmora, Meldor: Waffenschmied",
"Balmora, Milie Hastien: Fine Clothier":"Balmora, Milie Hastien: Schneiderin",
"Balmora, Morag Tong Guild":"Balmora, Morag Tong, Gilde",
"Balmora, Nalcarya of White Haven: Fine Alchemist":"Balmora, Nalcarya von Weißhafen: Alchemistin",
"Balmora, Nerano Manor":"Balmora, Haus Nerano",
"Balmora, Nine Toes' House":"Balmora, Neunzehs Haus",
"Balmora, Rarayn Radarys' House":"Balmora, Rarayn Radarys Haus",
"Balmora, Ra'Virr: Trader":"Balmora, Ra'Virr: Händler",
"Balmora, Rithleen's House":"Balmora, Rithleens Haus",
"Balmora, South Wall Cornerclub":"Balmora, Südwall-Taverne",
"Balmora, Temple":"Balmora, Tempel",
"Balmora, The Razor Hole":"Balmora, Die Klingengrube",
"Balmora, Tsiya's House":"Balmora, Tsiyas Haus",
"Balmora, Tyermaillin's House":"Balmora, Tyermaillins Haus",
"Balmora, Tyravel Manor":"Balmora, Haus Tyravel",
"Balmora, Vorar Helas' House":"Balmora, Vorar Helas Haus",
"Balmora, Vori's House":"Balmora, Voris Haus",
"Balmora, Western Guard Tower North":"Balmora, Westlicher Wachturm, Nord",
"Balmora, Western Guard Tower South":"Balmora, Westlicher Wachturm, Süd",
"Balur's Farmhouse":"Balurs Bauernhaus",
"Band Egg Mine":"Band, Eiermine",
"Baram Ancestral Tomb":"Beram-Ahnengruft",
"Bensamsi":"Bensamsi",
"Bensiberib Camp, Odaishah's Yurt":"Bensiberib-Lager, Odaishahs Zelt",
"Beran Ancestral Tomb":"Beran-Ahnengruft",
"Berandas":"Berandas",
"Berandas, Keep, Bottom Level":"Berandas, Festung, Unterste Ebene",
"Berandas, Keep, Top Level":"Berandas, Festung, Oberste Ebene",
"Berandas, Propylon Chamber":"Berandas, Propylon-Kammer",
"Berandas, Underground":"Berandas, Untergrund",
"Beshara":"Beshara",
"Big Head's Shack":"Großkopfs Hütte",
"Bthanchend":"Bthanchend",
"Bthuand":"Bthuand",
"Bthungthumz":"Bthungthumz",
"Buckmoth Legion Fort":"Festung der Buckfalter-Legion",
"Buckmoth Legion Fort, Interior":"Festung der Buckfalter-Legion, Innen",
"Buckmoth Legion Fort, Prison":"Festung der Buckfalter-Legion, Gefängnis",
"Buckmoth Legion Fort, Towers":"Festung der Buckfalter-Legion, Türme",
"Caldera":"Caldera",
"Caldera Mine":"Caldera-Mine",
"Caldera, Bashuk gra-Bat's House":"Caldera, Bashuk gra-Bats Haus",
"Caldera, Canodia Felannus' House":"Caldera, Canodia Felannus' Haus",
"Caldera, Dro'Shavir's House":"Caldera, Dro'Shavirs Haus",
"Caldera, Elmussa Damori's House":"Caldera, Elmussa Damoris Haus",
"Caldera, Falanaamo: Clothier":"Caldera, Falanaamo: Schneider",
"Caldera, Ghorak Manor":"Caldera, Haus Ghorak",
"Caldera, Governor's Hall":"Caldera, Halle des Regenten",
"Caldera, Guild of Mages":"Caldera, Magiergilde",
"Caldera, Hodlismod: Armorer":"Caldera, Hodlismod: Waffenschmied",
"Caldera, Irgola: Pawnbroker":"Caldera, Irgola: Pfandleiher",
"Caldera, Keel-Raniur's House":"Caldera, Keel-Raniurs Haus",
"Caldera, Mining Bunkhouse":"Caldera, Minen, Unterkünfte",
"Caldera, Mining Company Office":"Caldera, Minen, Schreibstube",
"Caldera, Mining Guard Tower":"Caldera, Wachturm der Mine",
"Caldera, Nedhelas' House":"Caldera, Nedhelas' Haus",
"Caldera, North Guard Towers":"Caldera, Nördliche Wachtürme",
"Caldera, Odairan Ashummi-Ammus' House":"Caldera, Odairan Ashummi-Ammus' Haus",
"Caldera, Shenk's Shovel":"Caldera, Shenks Hütte",
"Caldera, Slave Shack One":"Caldera, Erste Sklavenhütte",
"Caldera, Slave Shack Two":"Caldera, Zweite Sklavenhütte",
"Caldera, South Guard Towers":"Caldera, Südliche Wachtürme",
"Caldera, Surane Leoriane's House":"Caldera, Surane Leorianes Haus",
"Caldera, Valvius Mevureius' House":"Caldera, Valvius Mevureius Haus",
"Caldera, Verick Gemain: Trader":"Caldera, Verick Gemain: Händler",
"Cavern of the Incarnate":"Höhle der Fleisch-Gewordenen",
"Character Stuff Wonderland":"Wunderland",
"Chun-Ook, Cabin":"Chun-Ook, Kabine",
"Chun-Ook, Lower Level":"Chun-Ook, Unterdeck",
"Chun-Ook, Upper Level":"Chun-Ook, Oberdeck",
"Clutter Warehouse - Everything Must Go!":"Trödelverkauf – Alles muss weg!",
"Corprusarium":"Corprusarium",
"Corprusarium Bowels":"Das Innere des Corprusariums",
"Dagon Fel":"Dagon Fel",
"Dagon Fel, Andre Maul's Tower":"Dagon Fel, Andre Maahuls Turm",
"Dagon Fel, Anja Swift-Sailer's House":"Dagon Fel, Anjah Segelschwinges Haus",
"Dagon Fel, End of the World Renter Rooms":"Dagon Fel, Gasthaus Zum Ende der Welt",
"Dagon Fel, Fanar Fork-Beard's House":"Dagon Fel, Fanar Forkbards Haus",
"Dagon Fel, Fjorrod's House":"Dagon Fel, Fjorrods Haus",
"Dagon Fel, Greidil Half-Troll's House":"Dagon Fel, Greidil Halbtrolls Haus",
"Dagon Fel, Heifnir: Trader":"Dagon Fel, Heifnir: Händler",
"Dagon Fel, Hurg's House":"Dagon Fel, Hurgs Haus",
"Dagon Fel, Itar the Gentle's House":"Dagon Fel, Haus von Itar dem Sanftmütigen",
"Dagon Fel, Mette's House":"Dagon Fel, Mettes Haus",
"Dagon Fel, Onmi Hard-mouth's House":"Dagon Fel, Onmi Hartmunds Haus",
"Dagon Fel, Sorkvild's Tower":"Dagon Fel, Sorkvilds Turm",
"Dagon Fel, The End of the World":"Dagon Fel, Das Ende der Welt",
"Dagon Fel, Vacant Tower":"Dagon Fel, Leer stehender Turm",
"Dagon Fel, Watch Tower":"Dagon Fel, Wachurm",
"Dagoth Ur":"Dagoth Ur",
"Dagoth Ur, Facility Cavern":"Dagoth Ur, Höhle",
"Dagoth Ur, Inner Facility":"Dagoth Ur, Innere Höhle",
"Dagoth Ur, Inner Tower":"Dagoth Ur, Innerer Turm",
"Dagoth Ur, Lower Facility":"Dagoth Ur, Untere Höhle",
"Dagoth Ur, Outer Facility":"Dagoth Ur, Äußere Höhle",
"Dareleth Ancestral Tomb":"Dareleth-Ahnengruft",
"Derelict Shipwreck, Cabin":"Verfallendes Schiffswrack, Kabine",
"Derelict Shipwreck, Lower Level":"Verfallendes Schiffswrack, Unterdeck",
"Derelict Shipwreck, Upper Level":"Verfallendes Schiffswrack, Oberdeck",
"Deserted Shipwreck, Cabin":"Verwaistes Schiffswrack, Kabine",
"Deserted Shipwreck, Lower Level":"Verwaistes Schiffswrack, Unterdeck",
"Deserted Shipwreck, Upper Level":"Verwaistes Schiffswrack, Oberdeck",
"Desolate Shipwreck, Cabin":"Zerfallenes Schiffswrack, Kabine",
"Desolate Shipwreck, Lower Level":"Zerfallenes Schiffswrack, Unterdeck",
"Desolate Shipwreck, Upper Level":"Zerfallenes Schiffswrack, Oberdeck",
"Dirara's Farmhouse":"Diraras Bauernhaus",
"Dissapla Mine":"Dissapla-Mine",
"Dralas Ancestral Tomb":"Dralas-Ahnengruft",
"Drath Ancestral Tomb":"Drath-Ahnengruft",
"Dreloth Ancestral Tomb":"Dreloth-Ahnengruft",
"Dren Plantation":"Dren-Plantage",
"Dren Plantation, Doves' Shack":"Dren-Plantage, Doves Hütte",
"Dren Plantation, Dren's Villa":"Dren-Plantage, Drens Herrenhaus",
"Dren Plantation, Guardhouse":"Dren-Plantage, Wachhaus",
"Dren Plantation, Helvi's Shack":"Dren-Plantage, Helvis Hütte",
"Dren Plantation, Hlevala's Shack":"Dren-Plantage, Hlevalas Hütte",
"Dren Plantation, Rethan's Shack":"Dren-Plantage, Rethans Hütte",
"Dren Plantation, Shipping House":"Dren-Plantage, Lager",
"Dren Plantation, Storage Shack":"Dren-Plantage, Lagerhaus",
"Dren Plantation, Tower Shack":"Dren-Plantage, Turmhütte",
"Dren Plantation, Verethi and Dralor":"Dren-Plantage, Verethi und Dralor",
"Drethan Ancestral Tomb":"Drethan-Ahnengruft",
"Drinith Ancestral Tomb":"Drinith-Ahnengruft",
"Drulene Falen's Hut":"Drulene Falens Hütte",
"Druscashti, Lower Level":"Druscashti, Untere Ebene",
"Druscashti, Upper Level":"Druscashti, Obere Ebene",
"Dubdilla":"Dubdilla",
"Dubdilla, Uncharted Caverns":"Dubdilla, Unbekannte Höhlen",
"Dubdilla, Uncharted Caverns, Lower":"Dubdilla, Unbekannte Höhlen, Untere Ebene",
"Dulo Ancestral Tomb":"Dulo-Ahnengruft",
"Dun-Ahhe":"Dun-Ahhe",
"Dunirai Caverns":"Dunirai-Höhlen",
"Dushariran, Shrine":"Dushariran, Schrein",
"Ebernanit, Shrine":"Ebernanit, Schrein",
"Ebonheart":"Ebenherz",
"Ebonheart, Argonian Mission":"Ebenherz, Argonische Mission",
"Ebonheart, East Empire Company Hall":"Ebenherz, Ost-Kaiserliche Händlergilde, Halle",
"Ebonheart, East Empire North Warehouse":"Ebenherz, Ost-Kaiserliche Händlergilde, Nördliches Warenhaus",
"Ebonheart, East Empire South Warehouse":"Ebenherz, Ost-Kaiserliche Händlergilde, Südliches Warenhaus",
"Ebonheart, Grand Council Chambers":"Ebenherz, Saal des Großen Rates",
"Ebonheart, Grand Council Chambers Tower":"Ebenherz, Turmsaal des Großen Rates",
"Ebonheart, Hawkmoth Legion Garrison":"Ebenherz, Garnison der Falkenfalter-Legion",
"Ebonheart, Hawkmoth Towers":"Ebenherz, Falkenfalter-Türme",
"Ebonheart, Imperial Chapels":"Ebenherz, Kaiserliche Kapellen",
"Ebonheart, Imperial Commission":"Ebenherz, Kaiserliche Kommission",
"Ebonheart, Imperial Guard Garrison":"Ebenherz, Garnison der Kaiserlichen Wachen",
"Ebonheart, Six Fishes":"Ebenherz, Sechs Fische",
"Ebonheart, Skyrim Mission":"Ebenherz, Himmelsrand-Mission",
"Ebonheart, Underground Caves":"Ebenherz, Unterirdische Höhlen",
"Elanius Camp, Yapal's Yurt":"Elanius-Lager, Yapals Zelt",
"Elf-Skerring, Cabin":"Elf-Skerring, Kabine",
"Elf-Skerring, Lower Level":"Elf-Skerring, Unterdeck",
"Elf-Skerring, Upper Level":"Elf-Skerring, Oberdeck",
"Elith-Pal Mine":"Elith-Pal-Mine",
"Eluba-Addon Egg Mine":"Eluba-Addon, Eiermine",
"Eluba-Addon Grotto":"Eluba-Addon-Grotte",
"Endusal, Kagrenac's study":"Endusal, Kagrenacs Arbeitszimmer",
"Erabenimsun Camp":"Erabenimsun-Lager",
"Erabenimsun Camp, Addut-Lamanu's Yurt":"Erabenimsun-Lager, Addut-Lamanus Zelt",
"Erabenimsun Camp, Ainab's Yurt":"Erabenimsun-Lager, Ainabs Zelt",
"Erabenimsun Camp, Ashkhan's Yurt":"Erabenimsun-Lager, Zelt des Ashkhan",
"Erabenimsun Camp, Ashu-Ahhe's Yurt":"Erabenimsun-Lager, Ashu-Ahhes Zelt",
"Erabenimsun Camp, Assemmus' Yurt":"Erabenimsun-Lager, Assemmus Zelt",
"Erabenimsun Camp, Han-Ammu's Yurt":"Erabenimsun-Lager, Han-Ammus Zelt",
"Erabenimsun Camp, Massarapal's Yurt":"Erabenimsun-Lager, Massarapals Zelt",
"Erabenimsun Camp, Ranabi's Yurt":"Erabenimsun-Lager, Ranabis Zelt",
"Erabenimsun Camp, Salattanat's Yurt":"Erabenimsun-Lager, Salattanats Zelt",
"Erabenimsun Camp, Wise Woman's Yurt":"Erabenimsun-Lager, Zelt der Weisen Frau",
"Eretammus-Sennammu Egg Mine":"Eretammus-Sennammu, Eiermine",
"Esutanamus, Shrine":"Esutanamus, Schrein",
"Fadathram Ancestral Tomb":"Fadathram-Ahnengruft",
"Fair Helas, Cabin":"Fair Helas, Kabine",
"Fair Helas, Lower Level":"Fair Helas, Unterdeck",
"Fair Helas, Upper Level":"Fair Helas, Oberdeck",
"Falas Ancestral Tomb":"Falas-Ahnengruft",
"Falasmaryon":"Falasmaryon",
"Falasmaryon, Lower Level":"Falasmaryon, Untere Ebene",
"Falasmaryon, Missun Akin's Hut":"Falasmaryon, Missun Akins Hütte",
"Falasmaryon, Propylon Chamber":"Falasmaryon, Propylon-Kammer",
"Falasmaryon, Sewers":"Falasmaryon, Abwasserkanäle",
"Falasmaryon, Upper Level":"Falasmaryon, Obere Ebene",
"Falensarano":"Falensarano",
"Falensarano, Lower Level":"Falensarano, Untere Ebene",
"Falensarano, Propylon Chamber":"Falensarano, Propylon-Kammer",
"Falensarano, Upper Level":"Falensarano, Obere Ebene",
"Falvillo's Endeavor, Cabin":"Falvillos Streben, Kabine",
"Falvillo's Endeavor, Lower Level":"Falvillos Streben, Unterdeck",
"Falvilo's Endeavor, Upper Level":"Falvillos Streben, Oberdeck",
"Favel Ancestral Tomb":"Favel-Ahnengruft",
"Fields of Kummu":"Felder von Kummu",
"Forgotten Shipwreck":"Vergessenes Schiffswrack",
"Forgotten Vaults of Anudnabia, Forge of Hilbongard":"Vergessene Gewölbe von Anudnabia, Hilbongard-Schmiede",
"Galom Daeus, Entry":"Galom Daeus, Eingang",
"Galom Daeus, Observatory":"Galom Daeus, Observatorium",
"Ghostgate":"Geisterpforte",
"Ghostgate, Temple":"Geisterpforte, Tempel",
"Ghostgate, Tower of Dawn":"Geisterpforte, Turm der Morgendämmerung",
"Ghostgate, Tower of Dawn Lower Level":"Geisterpforte, Turm der Morgendämmerung, Untere Ebene",
"Ghostgate, Tower of Dusk":"Geisterpforte, Turm der Abenddämmerung",
"Ghostgate, Tower of Dusk Lower Level":"Geisterpforte, Turm der Abenddämmerung, Untere Ebene",
"Gimothran Ancestral Tomb":"Gimothran-Ahnengruft",
"Ginith Ancestral Tomb":"Ginith-Ahnengruft",
"Gnaar Mok":"Gnaar Mok",
"Gnaar Mok, Anglalos's Shack":"Gnaar Mok, Anglalos' Hütte",
"Gnaar Mok, Arenim Manor":"Gnaar Mok, Haus Arenim",
"Gnaar Mok, Caryarel's Shack":"Gnaar Mok, Caryarels Hütte",
"Gnaar Mok, Druegh-jigger's Rest":"Gnaar Mok, Dreugh-jiggers Ruh",
"Gnaar Mok, Jerian Dolbanitte's Shack":"Gnaar Mok, Jerian Dolbanittes Hütte",
"Gnaar Mok, Mush-Mere's Shack":"Gnaar Mok, Mush-Meres Hütte",
"Gnaar Mok, Nadene Rotheran's Shack":"Gnaar Mok, Nadene Rotherans Hütte",
"Gnaar Mok, Rostlogi's Shack":"Gnaar Mok, Rostlogis Hütte",
"Gnisis":"Gnisis",
"Gnisis, Abelmawia Hut":"Gnisis, Abelmawias Hütte",
"Gnisis, Almu Cave Dwelling":"Gnisis, Almu-Höhle",
"Gnisis, Arvs-Drelen":"Gnisis, Arvs-Drelen",
"Gnisis, Barracks":"Gnisis, Baracken",
"Gnisis, Bethamez":"Gnisis, Bethamez",
"Gnisis, Dinadad Hut":"Gnisis, Dinadads Hütte",
"Gnisis, Eggmine":"Gnisis, Eiermine",
"Gnisis, Fort Darius":"Gnisis, Darius-Festung",
"Gnisis, Lasamsi Cave Dwelling":"Gnisis, Lasamsi-Höhle",
"Gnisis, Lower Eggmine":"Gnisis, Untere Eiermine",
"Gnisis, Madach Tradehouse":"Gnisis, Handelshaus Madach",
"Gnisis, Man-llu Hut":"Gnisis, Man-llus Hütte",
"Gnisis, Mantiti Cave Dwelling":"Gnisis, Mantiti-Höhle",
"Gnisis, Shand Hut":"Gnisis, Shands Hütte",
"Gnisis, Shishara Hut":"Gnisis, Shisharas Hütte",
"Gnisis, Tansumiran Cave Dwelling":"Gnisis, Tansumiran-Höhle",
"Gnisis, Temple":"Gnisis, Tempel",
"Gnisis, Underground Stream":"Gnisis, Unterirdischer Fluss",
"Gnisis, Vabdas Hut":"Gnisis, Vabdas Hütte",
"Gnisis, Yahaz Hut":"Gnisis, Yahaz' Hütte",
"Gro-Bagrat Plantation":"Gro-Bagrat-Plantage",
"Grytewake, Cabin":"Grytewake, Kabine",
"Grytewake, Lower Level":"Grytewake, Unterdeck",
"Grytewake, Upper Level":"Grytewake, Oberdeck",
"Habinbaes":"Habinbaes",
"Hairat-Vassamsi Egg Mine":"Hairat-Vassamsi, Eiermine",
"Hairat-Vassamsi Egg Mine, Queen's Lair":"Hairat-Vassamsi, Eiermine, Nest der Königin",
"Halit Mine":"Halit-Mine",
"Hanud":"Hanud",
"Hanud, Tower":"Hanud, Turm",
"Hassour":"Hassour",
"Hassour, Shrine":"Hassour, Schrein",
"Hawia Egg Mine":"Hawia, Eiermine",
"Helan Ancestral Tomb":"Helan-Ahnengruft",
"Helas Ancestral Tomb":"Helas-Ahnengruft",
"Heleran Ancestral Tomb":"Heleran-Ahnengruft",
"Heran Ancestral Tomb":"Heran-Ahnengruft",
"Hinnabi":"Hinnabi",
"Hla Oad":"Hla Oad",
"Hla Oad, Fadila Balvel's House":"Hla Oad, Fadila Balvels Haus",
"Hla Oad, Fatleg's Drop Off":"Hla Oad, Fettis Versteck",
"Hla Oad, Murudius Flaeus's House":"Hla Oad, Murudius Flaeus’ Haus",
"Hla Oad, Okur's House":"Hla Oad, Okurs Haus",
"Hla Oad, Relien Rirne's House":"Hla Oad, Relien Rirnes Haus",
"Hla Oad, Shurkul gro-Sharga's House":"Hla Oad, Shurkul gro-Shargas Haus",
"Hlaalu Ancestral Tomb":"Hlaalu-Ahnengruft",
"Hleran Ancestral Tomb":"Hleran-Ahnengruft",
"Hlervi Ancestral Tomb":"Hlervi-Ahnengruft",
"Hlervu Ancestral Tomb":"Hlervu-Ahnengruft",
"Hlormaren":"Hlormaren",
"Hlormaren, Dome":"Hlormaren, Kuppel",
"Hlormaren, Keep, Bottom Level":"Hlormaren, Festung, Unterste Ebene",
"Hlormaren, Keep, Top Level":"Hlormaren, Festung, Oberste Ebene",
"Hlormaren, Propylon Chamber":"Hlormaren, Propylon-Kammer",
"Hlormaren, Sewers":"Hlormaren, Abwasserkanäle",
"Hlormaren, Underground":"Hlormaren, Untergrund",
"Holamayan":"Holamayan",
"Holamayan Monastery":"Holamayan-Kloster",
"Ibar-Dad":"Ibar-Dad",
"Ibishammus, Shrine":"Ibishammus, Schrein",
"Ienith Ancestral Tomb":"Ienith-Ahnengruft",
"Ihinipalit, Shrine":"Ihinipalit, Schrein",
"Ilanipu Grotto":"Ilanipu-Grotte",
"Ilunibi, Blackened Heart":"Ilunibi, Schwarzes Herz",
"Ilunibi, Carcass of the Saint":"Ilunibi, Leichnam des Heiligen",
"Ilunibi, Marowak's Spine":"Ilunibi, Marowaks Rücken",
"Ilunibi, Soul's Rattle":"Ilunibi, Seelenklapper",
"Ilunibi, Tainted Marrow":"Ilunibi, Beflecktes Mark",
"Imperial Prison Ship":"Kaiserliches Gefangenenschiff",
"Inanius Egg Mine":"Inanius, Eiermine",
"Indalen Ancestral Tomb":"Indalen-Ahnengruft",
"Indaren Ancestral Tomb":"Indaren-Ahnengruft",
"Indarys Manor":"Indarys-Anwesen",
"Indarys Manor, Berendas' House":"Indarys-Anwesen, Berendas' Haus",
"Indarys Manor, Manor Services":"Indarys-Anwesen, Dienste",
"Indarys Manor, Raram's House":"Indarys-Anwesen, Rarams Haus",
"Indoranyon":"Indoranyon",
"Indoranyon, Propylon Chamber":"Indoranyon, Propylon-Kammer",
"Kaushtababi Camp, Adibael's Yurt":"Kaushtababi-Lager, Adibaels Zelt",
"Kaushtarari, Shrine":"Kaushtarari, Schrein",
"ken's test hole":"Kens Testloch",
"Khartag Point":"Khartag",
"Khuul":"Khuul",
"Khuul, Aldi's Shack":"Khuul, Aldhis Hütte",
"Khuul, Brurid's Shack":"Khuul, Brurids Hütte",
"Khuul, Endris Dilmyn's Shack":"Khuul, Endris Dilmyns Hütte",
"Khuul, Helga's Shack":"Khuul, H'lgis Hütte",
"Khuul, Miron Garer's Shack":"Khuul, Miron Garers Hütte",
"Khuul, Nelmyne Andules's Shack":"Khuul, Nelmyne Andules’ Hütte",
"Khuul, Rivame Samandas's Shack":"Khuul, Rivame Samandas’ Hütte",
"Khuul, Svadstar's Shack":"Khuul, Svadstars Hütte",
"Khuul, Thongar's Tradehouse":"Khuul, Thongars Handelshaus",
"Koal Cave":"Kohlehöhle",
"Koal Cave Entrance":"Eingang der Koal-Höhle",
"Kogoruhn":"Kogoruhn",
"Kogoruhn, Bleeding Heart":"Kogoruhn, Blutendes Herz",
"Kogoruhn, Charma's Breath":"Kogoruhn, Charmas Atem",
"Kogoruhn, Dome of Pollock's Eve":"Kogoruhn, Pollocks Kuppel",
"Kogoruhn, Dome of Urso":"Kogoruhn, Ursos Kuppel",
"Kogoruhn, Hall of Maki":"Kogoruhn, Makis Halle",
"Kogoruhn, Hall of Phisto":"Kogoruhn, Phistos Halle",
"Kogoruhn, Hall of the Watchful Touch":"Kogoruhn, Halle des Wachsamens Gefühls",
"Kogoruhn, Nabith Waterway":"Kogoruhn, Nabith-Kanal",
"Kogoruhn, Temple of Fey":"Kogoruhn, Tempel der Todgeweihten",
"Kogoruhn, Vault of Aerode":"Kogoruhn, Aerodes Gewölbe",
"Kora-Dur":"Kora-Dur",
"Kudanat":"Kudanat",
"Kumarahaz":"Kumarahaz",
"Kunirai":"Kunirai",
"Kushtashpi, Shrine":"Kushtashpi, Schrein",
"Llando Ancestral Tomb":"Llando-Ahnengruft",
"Lleran Ancestral Tomb":"Lleran-Ahnengruft",
"Llervu Ancestral Tomb":"Llervu-Ahnengruft",
"Llirala's Shack":"Lliralas Hütte",
"Llovyn's Farmhouse":"Llovyns, Bauernhaus",
"Lonely Shipwreck, Cabin":"Einsames Schiffswrack, Kabine",
"Lonely Shipwreck, Lower Level":"Einsames Schiffswrack, Unterdeck",
"Lonely Shipwreck, Upper Level":"Einsames Schiffswrack, Oberdeck",
"Lonesome Shipwreck, Cabin":"Verschollenes Schiffswrack, Kabine",
"Lonesome Shipwreck, Lower Level":"Verschollenes Schiffswrack, Unterdeck",
"Lonesome Shipwreck, Upper Level":"Verschollenes Schiffswrack, Oberdeck",
"Lost Shipwreck, Cabin":"Aufgegebenes Schiffswrack, Kabine",
"Lost Shipwreck, Lower Level":"Aufgegebenes Schiffswrack, Unterdeck",
"Lost Shipwreck, Upper Level":"Aufgegebenes Schiffswrack, Oberdeck",
"Maar Gan":"Maar Gan",
"Maar Gan, Andus Tradehouse":"Maar Gan, Andus Handelshaus",
"Maar Gan, Assi Serimilk's Hut":"Maar Gan, Assi Serimilks Hütte",
"Maar Gan, Assirari Zama-Rasour's Hut":"Maar Gan, Assirari Zama-Rasours Hütte",
"Maar Gan, Garry's Hut":"Maar Gan, Garrys Hütte",
"Maar Gan, Guard Tower 1":"Maar Gan, Wachturm 1",
"Maar Gan, Guard Tower 2":"Maar Gan, Wachturm 2",
"Maar Gan, Guard Tower 3":"Maar Gan, Wachturm 3",
"Maar Gan, Huleen's Hut":"Maar Gan, Huleens Hütte",
"Maar Gan, Kind Erushara's Hut":"Maar Gan, Khind Erusharas Hütte",
"Maar Gan, Mabrelle Geles's Hut":"Maar Gan, Mabrelle Geles's Hütte",
"Maar Gan, Outpost":"Maar Gan, Außenposten",
"Maar Gan, Shilipuran Zama-Rasour's Hut":"Maar Gan, Shilipuran Zama-Rasours Hütte",
"Maar Gan, Shrine":"Maar Gan, Schrein",
"Maar Gan, Tashpi Ashibael's Hut":"Maar Gan, Tashpi Ashibaels Hütte",
"Maar Gan, Ulisamsi Shaddarnuran's Hut":"Maar Gan, Ulisamsi Shaddarnurans Hütte",
"Maar Gan, Yeherradad's Hut":"Maar Gan, Yeherradads Hütte",
"Mababi":"Mababi",
"Maba-Ilu":"Maba-Ilu",
"Madas Grotto":"Madas-Grotte",
"Madas-Zebba Egg Mine":"Madas-Zebba, Eiermine",
"Maelkashishi, Shrine":"Maelkashishi, Schrein",
"Maelkashishi, Shrine, Forgotten Galleries":"Maelkashishi, Schrein, Vergessene Empore",
"Maelu Egg Mine":"Maelu, Eiermine",
"Maesa-Shammus Egg Mine":"Maesa-Shammus, Eiermine",
"Magas Volar":"Magas Volar",
"Mallapi":"Mallapi",
"Malmus Grotto":"Malmus-Grotte",
"Mamaea, Sanctum of Awakening":"Mamaea, Heiligtum des Erwachens",
"Mamaea, Sanctum of Black Hope":"Mamaea, Heiligtum der Schwarzen Hoffnung",
"Mamaea, Shrine of Pitted Dreams":"Mamaea, Schrein der Düsteren Träume",
"Mamshar-Disamus Camp, Maesat's Yurt":"Mamshar-Disamus Lager, Maesats Zelt",
"Manat's Farmhouse":"Manats Bauernhaus",
"Mannammu":"Mannammu",
"Maran-Adon":"Maran-Adon",
"Marandus":"Marandus",
"Marandus, Dome":"Marandus, Kuppel",
"Marandus, Lower Level":"Marandus, Untere Ebene",
"Marandus, Propylon Chamber":"Marandus, Propylon-Kammer",
"Marandus, Upper Level":"Marandus, Obere Ebene",
"Maren Ancestral Tomb":"Maren-Ahnengruft",
"Mark's Vampire Test Cell":"Marks Vampir-Testzelle",
"Marvani Ancestral Tomb":"Marvani-Ahnengruft",
"Massahanud Camp, Sargon's Yurt":"Massahanud-Lager, Sargons Zelt",
"Massama Cave":"Massama-Höhle",
"Masseranit":"Masseranit",
"Mat":"Mat",
"Matus-Akin Egg Mine":"Matus-Akin, Eiermine",
"Matus-Akin Egg Mine, Queen's Lair":"Eiermine Matus-Akin, Nest der Königin",
"Mausur Caverns":"Mausur-Höhlen",
"Mawia":"Mawia",
"Mila-Nipal, Manat's Yurt":"Mila-Nipal, Manats Zelt",
"Milk":"Mylk",
"Minabi":"Minabi",
"Minabi, Bandit Lair":"Minabi, Banditenversteck",
"Ministry of Truth, Hall of Processing":"Ministerium der Wahrheit, Verfahrenssaal",
"Ministry of Truth, Holding Cells":"Ministerium der Wahrheit, Arrestzellen",
"Ministry of Truth, Prison Keep":"Ministerium der Wahrheit, Gefängnis",
"Missamsi":"Missamsi",
"Missir-Dadalit Egg Mine":"Missir-Dadalit, Eiermine",
"Molag Mar":"Molag Mar",
"Molag Mar, Armigers Stronghold":"Molag Mar, Festung der Kriegswappenträger",
"Molag Mar, Canalworks":"Molag Mar, Kanäle",
"Molag Mar, Redoran Stronghold":"Molag Mar, Redoranische Festung",
"Molag Mar, Saetring the Nord: Smith":"Molag Mar, Saetring der Nord: Schmied",
"Molag Mar, St. Veloth's Hostel":"Molag Mar, Herberge zum Hl. Veloth",
"Molag Mar, Temple":"Molag Mar, Tempel",
"Molag Mar, The Pilgrim's Rest":"Molag Mar, Herberge Zum Wallfahrer",
"Molag Mar, Underworks":"Molag Mar, Unterirdische Kanäle",
"Molag Mar, Vasesius Viciulus: Trader":"Molag Mar, Vasesius Viciulus: Händler",
"Molag Mar, Waistworks":"Molag Mar, Bodensektion",
"Moonmoth Legion Fort":"Festung der Mondfalter-Legion",
"Moonmoth Legion Fort, Interior":"Festung der Mondfalter-Legion, Innenbereich",
"Moonmoth Legion Fort, Prison Towers":"Festung der Mondfalter-Legion, Gefängnistürme",
"Morvayn Manor":"Haus Morvayn",
"Mount Assarnibibi":"Assarnibibiberg",
"Mount Kand":"Kandberg",
"Mount Kand, Cavern":"Kandberg, Höhle",
"Mudan Grotto":"Mudan-Grotte",
"Mudan, Central Vault":"Mudan, Gewölbe",
"Mudan, Lost Dwemer Checkpoint":"Mudan, Alter Dwemer-Kontrollpunkt",
"Mudan, Right Tower":"Mudan, Rechter Turm",
"Mudan-Mul Egg Mine":"Mudan-Mul, Eiermine",
"Mul Grotto":"Mul-Grotte",
"Mzahnch":"Mzahnch",
"Mzahnch Lower Level":"Mzahnch, Untere Ebene",
"Mzahnch Ruin":"Ruine Mzahnch",
"Mzanchend":"Mzanchend",
"Mzuleft":"Mzuleft",
"Mzuleft Ruin":"Ruine Mzuleft",
"Nallit":"Nallit",
"Nammu":"Nammu",
"Nchardahrk":"Nchardahrk",
"Nchardumz":"Nchardumz",
"Nchardumz Lower Level":"Nchardumz, Untere Ebene",
"Nchuleft":"Nchuleft",
"Nchuleft Ruin":"Ruine Nchuleft",
"Nchuleftingth":"Nchuleftingth",
"Nchuleftingth, Lower Levels":"Nchuleftingth, Untere Ebenen",
"Nchuleftingth, Test of Pattern":"Nchuleftingth, Prüfung der Muster",
"Nchuleftingth, Upper Levels":"Nchuleftingth, Obere Ebenen",
"Nchurdamz":"Nchurdamz",
"Nchurdamz, Interior":"Nchurdamz, Innenbereich",
"Neglected Shipwreck, Cabin":"Verrottendes Schiffswrack, Kabine",
"Neglected Shipwreck, Lower Level":"Verrottendes Schiffswrack, Unterdeck",
"Neglected Shipwreck, Upper Level":"Verrottendes Schiffswrack, Oberdeck",
"Nelas Ancestral Tomb":"Nelas-Ahnengruft",
"Nerano Ancestral Tomb":"Nerano-Ahnengruft",
"Nilera's Farmhouse":"Nileras Bauernhaus",
"Nimawia Grotto":"Nimawia-Grotte",
"Nissintu":"Nissintu",
"Norvayn Ancestral Tomb":"Norvayn-Ahnengruft",
"Nund":"Nund",
"Obscure Shipwreck, Cabin":"Düsteres Schiffswrack, Kabine",
"Obscure Shipwreck, Lower Level":"Düsteres Schiffswrack, Unterdeck",
"Obscure Shipwreck, Upper Level":"Düsteres Schiffswrack, Oberdeck",
"Odai Plateau":"Odai-Plateau",
"Odaishah":"Odaishah",
"Odibaal":"Odibaal",
"Odirnamat":"Odirnamat",
"Odirniran":"Odirniran",
"Odirniran, Tower":"Odirniran, Turm",
"Odrosal":"Odrosal",
"Odrosal, Dwemer Training Academy":"Odrosal, Ausbildungsakademie der Dwemer",
"Odrosal, Tower":"Odrosal, Turm",
"Omalen Ancestral Tomb":"Omalen-Ahnengruft",
"Omani Manor":"Haus Omani",
"Omaren Ancestral Tomb":"Omaren-Ahnengruft",
"Onnissiralis, Shrine":"Onnissiralis, Schrein",
"Orethi Ancestral Tomb":"Orethi-Ahnengruft",
"Othrelas Ancestral Tomb":"Othrelas-Ahnengruft",
"Palansour":"Palansour",
"Panabanit-Nimawia Egg Mine":"Panabanit-Nimawia, Eiermine",
"Panat":"Panat",
"Panud Egg Mine":"Panud, Eiermine",
"Pelagiad":"Pelagiad",
"Pelagiad, Adanja's House":"Pelagiad, Adanjas Haus",
"Pelagiad, Ahnassi's House":"Pelagiad, Ahnassis Haus",
"Pelagiad, Dralas Gilu's House":"Pelagiad, Dralas Gilus Haus",
"Pelagiad, Erval's House":"Pelagiad, Ervals Haus",
"Pelagiad, Farusea Salas' House":"Pelagiad, Farusea Salas’ Haus",
"Pelagiad, Fort Pelagiad":"Pelagiad, Festung Pelagiad",
"Pelagiad, Guard Tower":"Pelagiad, Wachturm",
"Pelagiad, Halfway Tavern":"Pelagiad, Herberge Zur Mitte",
"Pelagiad, Junal-lei's House":"Pelagiad, Junal-leis Haus",
"Pelagiad, Madres Navur's House":"Pelagiad, Madres Navurs Haus",
"Pelagiad, Mebestien Ence: Trader":"Pelagiad, Mebestien Ence: Händler",
"Pelagiad, Murberius Harmevus' House":"Pelagiad, Murberius Harmevus’ Haus",
"Pelagiad, North Wall":"Pelagiad, Nordmauer",
"Pelagiad, South Wall":"Pelagiad, Südmauer",
"Pelagiad, Uulernil : Armorer":"Pelagiad, Uulernil: Waffenschmied",
"Piernette's Farmhouse":"Piernettes Bauernhaus",
"Pinsun":"Pinsun",
"Piran":"Piran",
"Prelude Shipwreck, Cabin":"Prelude-Schiffswrack, Kabine",
"Prelude Shipwreck, Lower Level":"Prelude-Schiffswrack, Unterdeck",
"Prelude Shipwreck, Upper Level":"Prelude-Schiffswrack, Oberdeck",
"Pudai Egg Mine":"Pudai, Eiermine",
"Pudai Egg Mine, Queen's Lair":"Pudai, Eiermine, Nest der Königin",
"Pulk":"Pulk",
"Punabi":"Punabi",
"Punammu":"Punammu",
"Punsabanit":"Punsabanit",
"Ramimilk, Shrine":"Ramimilk, Schrein",
"Randas Ancestral Tomb":"Randas-Ahnengruft",
"Ravel Ancestral Tomb":"Ravel-Ahnengruft",
"Raviro Ancestral Tomb":"Raviro-Ahnengruft",
"Rayna Drolan's Shack":"Rayna Drolans Hütte",
"Redas Ancestral Tomb":"Redas-Ahnengruft",
"Redoran interior":"Redoran-Innenbereich",
"Redoran interior2":"Redoran-Innenbereich2",
"Releth Ancestral Tomb":"Releth-Ahnengruft",
"Reloth Ancestral Tomb":"Reloth-Ahnengruft",
"Remote Shipwreck, Cabin":"Entferntes Schiffswrack, Kabine",
"Remote Shipwreck, Lower Level":"Entferntes Schiffswrack, Unterdeck",
"Remote Shipwreck, Upper Level":"Entferntes Schiffswrack, Oberdeck",
"Rethan Manor":"Haus Rethan",
"Rethan Manor, Berendas' House":"Haus Rethan, Berendas’ Haus",
"Rethan Manor, Drelas' House":"Haus Rethan, Drelas’ Haus",
"Rethan Manor, Gols' House":"Haus Rethan, Gols’ Haus",
"Rethan Manor, Tures' House":"Haus Rethan, Tures’ Haus",
"Rethandus Ancestral Tomb":"Rethandus-Ahnengruft",
"Rissun":"Rissun",
"Rothan Ancestral Tomb":"Rothan-Ahnengruft",
"Rotheran":"Rotheran",
"Rotheran, Arena":"Rotheran, Arena",
"Rotheran, Communal Hut":"Rotheran, Gemeindehütte",
"Rotheran, Propylon Chamber":"Rotheran, Propylon-Kammer",
"Sadrith Mora":"Sadrith Mora",
"Sadrith Mora, Anis Seloth: Alchemist":"Sadrith Mora, Anis Seloth: Alchemistin",
"Sadrith Mora, Balen Vendu: Monk":"Sadrith Mora, Balen Vendu: Mönchsdienste",
"Sadrith Mora, Dirty Muriel's Cornerclub":"Sadrith Mora, Zur Dreckigen Muriel",
"Sadrith Mora, Fara's Hole in the Wall":"Sadrith Mora, Faras Loch in der Wand",
"Sadrith Mora, Gateway Inn":"Sadrith Mora, Taverne Zum Torbogen",
"Sadrith Mora, Gateway Inn: North Wing":"Sadrith Mora, Taverne Zum Torbogen, Nordflügel",
"Sadrith Mora, Gateway Inn: South Wing":"Sadrith Mora, Taverne Zum Torbogen, Südflügel",
"Sadrith Mora, Gateway Inn: West Wing":"Sadrith Mora, Taverne Zum Torbogen, Westflügel",
"Sadrith Mora, Hleras Gidren's House":"Sadrith Mora, Hleras Gidrens Haus",
"Sadrith Mora, Llaalam Madalas: Mage":"Sadrith Mora, Llaalam Madalas: Magier",
"Sadrith Mora, Madran Ulvel's House":"Sadrith Mora, Madran Ulvels Haus",
"Sadrith Mora, Meluria Seleth's House":"Sadrith Mora, Meluria Seleths Haus",
"Sadrith Mora, Milara Vedran's House":"Sadrith Mora, Milara Vedrans Haus",
"Sadrith Mora, Morag Tong Guild":"Sadrith Mora, Morag Tong, Gilde",
"Sadrith Mora, Nevrila Areloth's House":"Sadrith Mora, Nevrila Areloths Haus",
"Sadrith Mora, Nirasa Aren's House":"Sadrith Mora, Nirasa Arens Haus",
"Sadrith Mora, Pierlette Rostorard: Apothecary":"Sadrith Mora, Pierlette Rostorard: Trankmischerin",
"Sadrith Mora, Rolis Garvon's House":"Sadrith Mora, Rolis Garvons Haus",
"Sadrith Mora, Tel Naga General Quarters":"Sadrith Mora, Tel Naga, Unterkünfte",
"Sadrith Mora, Tel Naga Great Hall":"Sadrith Mora, Tel Naga, große Halle",
"Sadrith Mora, Tel Naga Upper Hall":"Sadrith Mora, Tel Naga, obere Halle",
"Sadrith Mora, Tel Naga Upper Tower":"Sadrith Mora, Tel Naga, oberer Turm",
"Sadrith Mora, Telvanni Council House":"Sadrith Mora, Telvanni-Ratshaus",
"Sadrith Mora, Telvanni Council House, Chambers":"Sadrith Mora, Telvanni-Ratshaus, Gemächer",
"Sadrith Mora, Telvanni Council House, Entry":"Sadrith Mora, Telvanni-Ratshaus, Eingang",
"Sadrith Mora, Telvanni Council House, Hermitage":"Sadrith Mora, Telvanni-Ratshaus, Klause",
"Sadrith Mora, Thervul Serethi: Healer":"Sadrith Mora, Thervul Serethi: Heiler",
"Sadrith Mora, Trendrus Dral's House":"Sadrith Mora, Trendrus Drals Haus",
"Sadrith Mora, Urtisa Romayn's House":"Sadrith Mora, Urtisa Romayns Haus",
"Sadrith Mora, Urtiso Faryon: Sorcerer":"Sadrith Mora, Urtiso Faryon: Hexenmeisterin",
"Sadrith Mora, Vaden Belas' House":"Sadrith Mora, Vaden Belas Haus",
"Sadrith Mora, Volmyni Dral's House":"Sadrith Mora, Volmyni Drals Haus",
"Sadrith Mora, Wolverine Hall":"Sadrith Mora, Wolfenhalle",
"Sadrith Mora, Wolverine Hall: Fighter's Guild":"Sadrith Mora, Wolfenhalle: Kriegergilde",
"Sadrith Mora, Wolverine Hall: Imperial Shrine":"Sadrith Mora, Wolfenhalle: Kaiserlicher Schrein",
"Sadrith Mora, Wolverine Hall: Mage's Guild":"Sadrith Mora, Wolfenhalle: Magiergilde",
"Sadryon Ancestral Tomb":"Sadryon-Ahnengruft",
"Salit Camp, Zalit's Yurt":"Salit-Lager, Zalits Zelt",
"Salit Camp, Zelay's Yurt":"Salit-Lager, Zelays Zelt",
"Salmantu":"Salmantu",
"Salmantu, Shrine":"Salmantu, Schrein",
"Salothan Ancestral Tomb":"Salothan-Ahnengruft",
"Salothran Ancestral Tomb":"Salothran-Ahnengruft",
"Salvel Ancestral Tomb":"Salvel-Ahnengruft",
"Samarys Ancestral Tomb":"Samarys-Ahnengruft",
"Sanabi":"Sanabi",
"Sanctus Shrine":"Sanktus-Schrein",
"Sandas Ancestral Tomb":"Sandas-Ahnengruft",
"Sandus Ancestral Tomb":"Sandus-Ahnengruft",
"Sanit":"Sanit",
"Sanit, Shrine":"Sanit, Schrein",
"Sanni":"Sanni",
"Sarano Ancestral Tomb":"Sarano-Ahnengruft",
"Saren Ancestral Tomb":"Saren-Ahnengruft",
"Sarethi Ancestral Tomb":"Sarethi-Ahnengruft",
"Sargon":"Sargon",
"Sarimisun-Assa Egg Mine":"Sarimisun-Assa, Eiermine",
"Sarimisun-Assa Egg Mine, Queen's Lair":"Sarimisun-Assa, Eiermine, Nest der Königin",
"Sarys Ancestral Tomb":"Sarys-Ahnengruft",
"Saturan":"Saturan",
"Savel Ancestral Tomb":"Savel-Ahnengruft",
"Senim Ancestral Tomb":"Senim-Ahnengruft",
"Sennananit":"Sennananit",
"Seran Ancestral Tomb":"Seran-Ahnengruft",
"Serano Ancestral Tomb":"Serano-Ahnengruft",
"Sethan Ancestral Tomb":"Sethan-Ahnengruft",
"Setus Egg Mine":"Setus, Eiermine",
"Seyda Neen":"Seyda Neen",
"Seyda Neen, Arrille's Tradehouse":"Seyda Neen, Arrilles Handelshaus",
"Seyda Neen, Census and Excise Office":"Seyda Neen, Zensus- und Steueramt",
"Seyda Neen, Census and Excise Warehouse":"Seyda Neen, Zensus- und Steueramt Lagerhaus",
"Seyda Neen, Draren Thiralas' House":"Seyda Neen, Draren Thiralas Haus",
"Seyda Neen, Eldafire's House":"Seyda Neen, Eldafires Haus",
"Seyda Neen, Erene Llenim's Shack":"Seyda Neen, Erene Llenims Hütte",
"Seyda Neen, Fargoth's House":"Seyda Neen, Fargoths Haus",
"Seyda Neen, Fine-Mouth's Shack":"Seyda Neen, Finomoldos Hütte",
"Seyda Neen, Foryn Gilnith's Shack":"Seyda Neen, Foryn Gilniths Hütte",
"Seyda Neen, Indrele Rathryon's Shack":"Seyda Neen, Indrele Rathryons Hütte",
"Seyda Neen, Lighthouse":"Seyda Neen, Leuchtturm",
"Seyda Neen, Terurise Girvayne's House":"Seyda Neen, Terurise Girvaynes Haus",
"Seyda Neen, Vodunius Nuccius' House":"Seyda Neen, Vodunius Nuccius’ Haus",
"Sha-Adnius":"Sha-Adnius",
"Shal":"Shal",
"Shallit":"Shallit",
"Shara":"Shara",
"Sharapli":"Sharapli",
"Shashmanu Camp, Anit's Yurt":"Shashmanu-Lager, Anits Zelt",
"Shashpilamat":"Shashpilamat",
"Shashpilamat, Shrine":"Shashpilamat, Schrein",
"Shashurari Camp, Zennammu's Yurt":"Shashurari-Lager, Zennammus Zelt",
"Shishara":"Shishara",
"Shishi":"Shishi",
"Shrine of Azura":"Azuras Schrein",
"Shulk Egg Mine":"Shulk, Eiermine",
"Shulk Egg Mine, Mining Camp":"Shulk, Eiermine, Schürflager",
"Shulk Egg Mine, Queen's Lair":"Shulk, Eiermine, Nest der Königin",
"Shunned Shipwreck, Cabin":"Gemiedenes Schiffswrack, Kabine",
"Shunned Shipwreck, Lower Level":"Gemiedenes Schiffswrack, Unterdeck",
"Shunned Shipwreck, Upper Level":"Gemiedenes Schiffswrack, Oberdeck",
"Shurdan-Raplay Egg Mine":"Shurdan-Raplay, Eiermine",
"Shurinbaal":"Shurinbaal",
"Shushan":"Shushan",
"Shushishi":"Shushishi",
"Sinamusa Egg Mine":"Sinamusa, Eiermine",
"Sinarralit Egg Mine":"Sinarralit, Eiermine",
"Sinsibadon":"Sinsibadon",
"Sjorvar Horse-Mouth's House":"Sjorvar Nüsters Haus",
"Small Farmhouse":"Kleines Gutshaus",
"Sobitbael Camp, Mal's Yurt":"Sobitbael-Lager, Mals Zelt",
"Sterdecan's Farmhouse":"Sterdecans Hof",
"Strange Shipwreck, Cabin":"Seltsames Schiffswrack, Kabine",
"Strange Shipwreck, Lower Level":"Seltsames Schiffswrack, Oberdeck",
"Strange Shipwreck, Upper Level":"Seltsames Schiffswrack, Unterdeck",
"Subdun":"Subdun",
"Subdun, Shrine":"Subdun, Schrein",
"Sud":"Sud",
"Sudanit Mine":"Sudanit, Mine",
"Sulipund":"Sulipund",
"Sur Egg Mine":"Sur, Eiermine",
"Suran":"Suran",
"Suran, Desele's House of Earthly Delights":"Suran, Deseles Haus der irdischen Freuden",
"Suran, Garothmuk gro-Muzgub: Smith":"Suran, Garothmuk gro-Muzgub: Schmied",
"Suran, Goldyn Belaram: Pawnbroker":"Suran, Goldyn Belaram: Pfandleiher",
"Suran, Guard Tower":"Suran, Wachturm",
"Suran, Ibarnadad Assirnarari: Apothecary":"Suran, Ibarnadad Assirnarari: Trankmischer",
"Suran, Oran Manor":"Suran, Haus Oran",
"Suran, Ralds Oril: Trader":"Suran, Ralds Oril: Händler",
"Suran, Ranosa Gilvayn: Outfitter":"Suran, Ranosa Gilvayn: Ausstatterin",
"Suran, Suran Slave Market":"Suran, Sklavenmarkt",
"Suran, Suran Temple":"Suran, Tempel",
"Suran, Suran Tradehouse":"Suran, Handelshaus",
"Suran, Verara Rendo: Clothier":"Suran, Verara Rendo: Schneiderin",
"Surirulk":"Surirulk",
"Tel Aruhn":"Tel Aruhn",
"Tel Aruhn, Aryne Telnim: Smith":"Tel Aruhn, Aryne Telnim: Schmiedin",
"Tel Aruhn, Bildren Areleth: Apothecary":"Tel Aruhn, Bildren Areleth: Trankmischer",
"Tel Aruhn, Ferele Athram: Trader":"Tel Aruhn, Ferele Athram: Händler",
"Tel Aruhn, Maren Uvaren: Enchanter":"Tel Aruhn, Maren Uvaren: Verzauberungen",
"Tel Aruhn, Plot and Plaster":"Tel Aruhn, Pech und Schwefel",
"Tel Aruhn, Tower Entry":"Tel Aruhn, Turmzugang",
"Tel Aruhn, Tower Living Quarters":"Tel Aruhn, Turm-Wohnquartiere",
"Tel Aruhn, Underground":"Tel Aruhn, Untergrund",
"Tel Aruhn, Upper Tower":"Tel Aruhn, Oberer Turm",
"Tel Branora":"Tel Branora",
"Tel Branora, Ervyna Hlervu's Shack":"Tel Branora, Ervyna Hlervus Hütte",
"Tel Branora, Evos Goran's House":"Tel Branora, Evos Gorans Haus",
"Tel Branora, Fadase Selvayn: Trader":"Tel Branora, Fadase Selvayn: Händlerin",
"Tel Branora, Fedar Davus's House":"Tel Branora, Fedar Davus’ Haus",
"Tel Branora, Galen Berer: Armorer":"Tel Branora, Galen Berer: Waffenschmied",
"Tel Branora, Giron Manas's Shack":"Tel Branora, Giron Manas’ Hütte",
"Tel Branora, Lower Tower":"Tel Branora, Unterer Turm",
"Tel Branora, Manos Vavyn's House":"Tel Branora, Manos Vavyns Haus",
"Tel Branora, Seryne Relas's House":"Tel Branora, Seryne Relas’ Haus",
"Tel Branora, Sethan's Tradehouse":"Tel Branora, Sethans Handelshaus",
"Tel Branora, Tower Dungeon":"Tel Branora, Turmverlies",
"Tel Branora, Tower Guardpost":"Tel Branora, Turm-Wachposten",
"Tel Branora, Upper Tower":"Tel Branora, Oberer Turm",
"Tel Branora, Upper Tower: Therana's Chamber":"Tel Branora, Oberer Turm: Theranas Kammern",
"Tel Fyr":"Tel Fyr",
"Tel Mora":"Tel Mora",
"Tel Mora, Berwen: Trader":"Tel Mora, Berwen: Händlerin",
"Tel Mora, Elegnan: Clothier":"Tel Mora, Elegnan: Schneiderin",
"Tel Mora, Jolda: Apothecary":"Tel Mora, Jolda: Trankmischerin",
"Tel Mora, Kirsty's House":"Tel Mora, Kirstys Haus",
"Tel Mora, Liette's House":"Tel Mora, Liettes Haus",
"Tel Mora, Lower Tower":"Tel Mora, Unterer Turm",
"Tel Mora, Nona's House":"Tel Mora, Nonas Haus",
"Tel Mora, Radras: Smith":"Tel Mora, Radras: Schmiedin",
"Tel Mora, The Covenant":"Tel Mora, Zum feierlichen Schwur",
"Tel Mora, Tower Services":"Tel Mora, Turm der Dienste",
"Tel Mora, Upper Tower":"Tel Mora, Oberer Turm",
"Tel Uvirith, Arelas' House":"Tel Uvirith, Arelas’ Haus",
"Tel Uvirith, Menas' House":"Tel Uvirith, Menas’ Haus",
"Tel Uvirith, Omavel's House":"Tel Uvirith, Omavels Haus",
"Tel Uvirith, Seleth's House":"Tel Uvirith, Seleths Haus",
"Tel Uvirith, Tower Dungeon":"Tel Uvirith, Turmverlies",
"Tel Uvirith, Tower Lower":"Tel Uvirith, Unterer Turm",
"Tel Uvirith, Tower Upper":"Tel Uvirith, Oberer Turm",
"Tel Vos":"Tel Vos",
"Tel Vos, Aryon's Chambers":"Tel Vos, Aryons Kammern",
"Tel Vos, Barracks and Armory":"Tel Vos, Kaserne und Waffenkammer",
"Tel Vos, Central Tower":"Tel Vos, Zentraler Turm",
"Tel Vos, Dungeon":"Tel Vos, Verlies",
"Tel Vos, Jail":"Tel Vos, Gefängnis",
"Tel Vos, Northeastern Tower":"Tel Vos, Nordöstlicher Turm",
"Tel Vos, Services Tower":"Tel Vos, Turm der Dienste",
"Tel Vos, Southern Tower":"Tel Vos, Südlicher Turm",
"Telasero":"Telasero",
"Telasero, Lower Level":"Telasero, Untere Ebene",
"Telasero, Propylon Chamber":"Telasero, Propylon-Kammer",
"Telasero, Upper Level":"Telasero, Obere Ebene",
"Telvayn Ancestral Tomb":"Telvayn-Ahnengruft",
"Thalas Ancestral Tomb":"Thalas-Ahnengruft",
"Tharys Ancestral Tomb":"Tharys-Ahnengruft",
"Thelas Ancestral Tomb":"Thelas-Ahnengruft",
"Thiralas Ancestral Tomb":"Thiralas-Ahnengruft",
"Tin-Ahhe":"Tin-Ahhe",
"ToddTest":"ToddTest",
"Tower of Tel Fyr, Hall of Fyr":"Turm von Tel Fyr, Halle von Fyr",
"Tower of Tel Fyr, Onyx Hall":"Turm von Tel Fyr, Onyxhalle",
"Tukushapal":"Tukushapal",
"Tukushapal, Sepulcher":"Tukushapal, Grabmal",
"Tureynulal":"Tureynulal",
"Tureynulal, Bladder of Clovis":"Tureynulal, Blase von Clovis",
"Tureynulal, Eye of Duggan":"Tureynulal, Auge von Duggan",
"Tureynulal, Eye of Thom Wye":"Tureynulal, Auge von Thom Wye",
"Tureynulal, Kagrenac's Library":"Tureynulal, Kagrenacs Bibliothek",
"Tusenend, Shrine":"Tusenend, Schrein",
"Ularradallaku, Shrine":"Ularradallaku, Schrein",
"Ules Manor":"Ules-Anwesen",
"Ules Manor, Slave Shack":"Ules-Anwesen, Sklavenhütte",
"Ules Manor, Slavemaster's Shack":"Ules-Anwesen, Hütte des Sklavenmeisters",
"Ulummusa":"Ulummusa",
"Uncharted Shipwreck, Lower Level":"Unentdecktes Schiffswrack, Kabine",
"Unchartered Shipwreck, Cabin":"Unentdecktes Schiffswrack, Unterdeck",
"Unchartered Shipwreck, Upper Level":"Unentdecktes Schiffswrack, Oberdeck",
"Unexplored Shipwreck, Cabin":"Unerforschtes Schiffswrack, Kabine",
"Unexplored Shipwreck, Lower Level":"Unerforschtes Schiffswrack, Unterdeck",
"Unexplored Shipwreck, Upper Level":"Unerforschtes Schiffswrack, Oberdeck",
"Unknown Shipwreck, Cabin":"Unbekanntes Schiffswrack, Kabine",
"Unknown Shipwreck, Lower Level":"Unbekanntes Schiffswrack, Unterdeck",
"Unknown Shipwreck, Upper Level":"Unbekanntes Schiffswrack, Oberdeck",
"Unmarked Shipwreck, Lower Level":"Nicht verzeichnetes Schiffswrack, Unterdeck",
"Unmarked Shipwreck, Upper Level":"Nicht verzeichnetes Schiffswrack, Oberdeck",
"Urshilaku Camp":"Urshilaku-Lager",
"Urshilaku Camp, Ahasour's Yurt":"Urshilaku-Lager, Ahasours Zelt",
"Urshilaku Camp, Ashkhan's Yurt":"Urshilaku-Lager, Zelt des Ashkhan",
"Urshilaku Camp, Kurapli's Yurt":"Urshilaku-Lager, Kuraplis Zelt",
"Urshilaku Camp, Maeli's Yurt":"Urshilaku-Lager, Maelis Zelt",
"Urshilaku Camp, Sakiran's Yurt":"Urshilaku-Lager, Sakirans Zelt",
"Urshilaku Camp, Shara's Yurt":"Urshilaku-Lager, Sharas Zelt",
"Urshilaku Camp, Shimsun's Yurt":"Urshilaku-Lager, Shimsuns Zelt",
"Urshilaku Camp, Wise Woman's Yurt":"Urshilaku-Lager, Zelt der Weisen Frau",
"Urshilaku Camp, Zabamund's Yurt":"Urshilaku-Lager, Zabamunds Zelt",
"Urshilaku Camp, Zanummu's Yurt":"Urshilaku-Lager, Zanummus Zelt",
"Urshilaku, Astral Burial":"Urshilaku, Astralgrab",
"Urshilaku, Fragile Burial":"Urshilaku, Bruchgrab",
"Urshilaku, Juno Burial":"Urshilaku, Juno-Grab",
"Urshilaku, Kakuna Burial":"Urshilaku, Kakuna-Grab",
"Urshilaku, Karma Burial":"Urshilaku, Karma-Grab",
"Urshilaku, Kefka Burial":"Urshilaku, Kefka-Grab",
"Urshilaku, Laterus Burial":"Urshilaku, Laterus-Grab",
"Uveran Ancestral Tomb":"Uveran-Ahnengruft",
"Uvirith's Grave":"Uviriths Grab",
"Valenvaryon":"Valenvaryon",
"Valenvaryon, Durz's Hut":"Valenvaryon, Durzs Hütte",
"Valenvaryon, Gashna's Hut":"Valenvaryon, Gashnas Hütte",
"Valenvaryon, Lambug's Hut":"Valenvaryon, Lambugs Hütte",
"Valenvaryon, Lurog's Hut":"Valenvaryon, Lurogs Hütte",
"Valenvaryon, Propylon Chamber":"Valenvaryon, Propylon-Kammer",
"Valenvaryon, Umug's Hut":"Valenvaryon, Umugs Hütte",
"Vandus Ancestral Tomb":"Vandus-Ahnengruft",
"Vansunalit Egg Mine":"Vansunalit, Eiermine",
"Vas":"Vas",
"Vas, Entry Level":"Vas, Zugangsebene",
"Vas, Tower":"Vas, Turm",
"Vassamsi Grotto":"Vassamsi-Grotte",
"Vassir-Didanat Cave":"Vassir-Didanat Höhle",
"Velas Ancestral Tomb":"Velas-Ahnengruft",
"Veloth Ancestral Tomb":"Veloth-Ahnengruft",
"Vemynal":"Vemynal",
"Vemynal, Hall of Torque":"Vemynal, Halle der Drehungen",
"Vemynal, Outer Fortress":"Vemynal, Äußere Festung",
"Venim Ancestral Tomb":"Venim-Ahnengruft",
"Verelnim Ancestral Tomb":"Verelnim-Ahnengruft",
"Vivec":"Vivec",
"Vivec, Agrippina Herennia: Clothier":"Vivec, Agrippina Herennia: Schneiderin",
"Vivec, Alusaron: Smith":"Vivec, Alusaron: Schmied",
"Vivec, Andilu Drothan: Alchemist":"Vivec, Andilu Drothan: Alchemistin",
"Vivec, Arena":"Vivec, Arena",
"Vivec, Arena Canalworks":"Vivec, Arena, Kanäle",
"Vivec, Arena Fighters Quarters":"Vivec, Arena, Quartiere der Kämpfer",
"Vivec, Arena Fighters Training":"Vivec, Arena, Kämpfer-Ausbildungsbereich",
"Vivec, Arena Hidden Area":"Vivec, Arena, Versteckter Bereich",
"Vivec, Arena Holding Cells":"Vivec, Arena, Zellen",
"Vivec, Arena Pit":"Vivec, Arena, Grube",
"Vivec, Arena Storage":"Vivec, Arena, Lager",
"Vivec, Arena Underworks":"Vivec, Arena, Unterirdische Kanäle",
"Vivec, Arena Waistworks":"Vivec, Arena, Bodensektion",
"Vivec, Aurane Frernis: Apothecary":"Vivec, Aurane Frernis: Trankmischerin",
"Vivec, Black Shalk Cornerclub":"Vivec, Taverne Zum Schwarzen Shalk",
"Vivec, Canon Offices":"Vivec, Kanonikat",
"Vivec, Canon Quarters":"Vivec, Kanoniker-Quartiere",
"Vivec, Curio Manor":"Vivec, Haus Curio",
"Vivec, Dralor Manor":"Vivec, Haus Dralor",
"Vivec, Elven Nations Cornerclub":"Vivec, Taverne Elfennation",
"Vivec, Foreign Quarter":"Vivec, Fremdenviertel",
"Vivec, Foreign Quarter Canalworks":"Vivec, Fremdenviertel, Kanäle",
"Vivec, Foreign Quarter Lower Waistworks":"Vivec, Fremdenviertel, Untere Bodensektion",
"Vivec, Foreign Quarter Plaza":"Vivec, Fremdenviertel, Platz",
"Vivec, Foreign Quarter Tomb":"Vivec, Fremdenviertel, Gruft",
"Vivec, Foreign Quarter Underworks":"Vivec, Fremdenviertel, Unterirdische Kanäle",
"Vivec, Foreign Quarter Upper Waistworks":"Vivec, Fremdenviertel, Obere Bodensektion",
"Vivec, Guild of Fighters":"Vivec, Kriegergilde",
"Vivec, Guild of Mages":"Vivec, Magiergilde",
"Vivec, Hall of Justice":"Vivec, Halle der Gerechtigkeit",
"Vivec, Hall of Justice Secret Library":"Vivec, Halle der Gerechtigkeit, Geheimbibliothek",
"Vivec, Hall of Wisdom":"VIvec, Halle der Weisheit",
"Vivec, Hall Underworks":"Vivec, Hallen, Unterirdische Kanäle",
"Vivec, High Fane":"Vivec, Hoher Tempel",
"Vivec, Hlaalu":"Vivec, Hlaalu",
"Vivec, Hlaalu Alchemist":"Vivec, Hlaalu, Alchimist",
"Vivec, Hlaalu Ancestral Vaults":"Vivec, Hlaalu, Ahnengewölbe",
"Vivec, Hlaalu Canalworks":"Vivec, Hlaalu, Kanäle",
"Vivec, Hlaalu Edryno Arethi's House":"Vivec, Hlaalu, Edryno Arethis Haus",
"Vivec, Hlaalu General Goods":"Vivec, Hlaalu, Waren aller Art",
"Vivec, Hlaalu Pawnbroker":"Vivec, Hlaalu, Pfandleiher",
"Vivec, Hlaalu Plaza":"Vivec, Hlaalu, Platz",
"Vivec, Hlaalu Prison Cells":"Vivec, Hlaalu, Gefängniszellen",
"Vivec, Hlaalu Records":"Vivec, Hlaalu, Archive",
"Vivec, Hlaalu Temple":"Vivec, Hlaalu, Tempel",
"Vivec, Hlaalu Treasury":"Vivec, Hlaalu, Schatzhaus",
"Vivec, Hlaalu Underworks":"Vivec, Hlaalu, Unterirdische Kanäle",
"Vivec, Hlaalu Vaults":"Vivec, Hlaalu, Gewölbe",
"Vivec, Hlaalu Waistworks":"Vivec, Hlaalu, Bodensektion",
"Vivec, Hlaalu Weaponsmith":"Vivec, Hlaalu, Waffenschmied",
"Vivec, Hlaren Residence":"Vivec, Hlaren-Residenz",
"Vivec, Jeanne: Trader":"Vivec, Jeanne: Händlerin",
"Vivec, Jobasha's Rare Books":"Vivec, Jobashas Seltene Bücher",
"Vivec, J'Rasha: Healer":"Vivec, J'Rasha: Heiler",
"Vivec, Justice Offices":"Vivec, Gesetzeshallen",
"Vivec, Library of Vivec":"Vivec, Bibliothek von Vivec",
"Vivec, Lucretinaus Olcinius: Trader":"Vivec, Lucretinaus Olcinius: Händler",
"Vivec, Mevel Fererus: Trader":"Vivec, Mevel Fererus: Händler",
"Vivec, Milo's Quarters":"Vivec, Milos Quartiere",
"Vivec, Miun-Gei: Enchanter":"Vivec, Miun-Gei: Verzauberungen",
"Vivec, No Name Club":"Vivec, Taverne ohne Namen",
"Vivec, Office of the Watch":"Vivec, Hallen der Wache",
"Vivec, Ordinator Barracks":"Vivec, Unterkünfte der Ordinatoren",
"Vivec, Palace of Vivec":"Vivec, Palast des Vivec",
"Vivec, Puzzle Canal, Center":"Vivec, Rätsel-Kanal, Zentrum",
"Vivec, Puzzle Canal, Level 1":"Vivec, Rätsel-Kanal, Ebene 1",
"Vivec, Puzzle Canal, Level 2":"Vivec, Rätsel-Kanal, Ebene 2",
"Vivec, Puzzle Canal, Level 3":"Vivec, Rätsel-Kanal, Ebene 3",
"Vivec, Puzzle Canal, Level 4":"Vivec, Rätsel-Kanal, Ebene 4",
"Vivec, Puzzle Canal, Level 5":"Vivec, Rätsel-Kanal, Ebene 5",
"Vivec, Ralen Tilvur: Smith":"Vivec, Ralen Tilvur: Schmied",
"Vivec, Redoran":"Vivec, Redoran",
"Vivec, Redoran Ancestral Vaults":"Vivec, Redoran, Ahnengewölbe",
"Vivec, Redoran Canalworks":"Vivec, Redoran, Kanäle",
"Vivec, Redoran Plaza":"Vivec, Redoran, Platz",
"Vivec, Redoran Prison Cells":"Vivec, Redoran, Gefängniszellen",
"Vivec, Redoran Records":"Vivec, Redoran, Archive",
"Vivec, Redoran Scout & Drillmaster":"Vivec, Redoran, Kundschafter und Ausbilder",
"Vivec, Redoran Smith":"Vivec, Redoran, Schmied",
"Vivec, Redoran Temple Shrine":"Vivec, Redoran, Tempelschrein",
"Vivec, Redoran Trader":"Vivec, Redoran, Händler",
"Vivec, Redoran Treasury":"Vivec, Redoran, Schatzhaus",
"Vivec, Redoran Underworks":"Vivec, Redoran, Unterirdische Kanäle",
"Vivec, Redoran Vaults":"Vivec, Redoran, Gewölbe",
"Vivec, Redoran Waistworks":"Vivec, Redoran, Bodensektion",
"Vivec, Saren Manor":"Vivec, Haus Saren",
"Vivec, Simine Fralinie: Bookseller":"Vivec, Simine Fralinie: Buchhändler",
"Vivec, St. Delyn":"Vivec, Hl. Delyn",
"Vivec, St. Delyn Canal North-One":"Vivec, Hl.Delyn, Kanal Nord-Eins",
"Vivec, St. Delyn Canal North-Three":"Vivec, Hl.Delyn, Kanal Nord-Drei",
"Vivec, St. Delyn Canal North-Two":"Vivec, Hl.Delyn, Kanal Nord-Zwei",
"Vivec, St. Delyn Canal South-One":"Vivec, Hl.Delyn, Kanal Süd-Eins",
"Vivec, St. Delyn Canal South-Three":"Vivec, Hl.Delyn, Kanal Süd-Drei",
"Vivec, St. Delyn Canal South-Two":"Vivec, Hl.Delyn, Kanal Süd-Zwei",
"Vivec, St. Delyn Canalworks":"Vivec, Hl.Delyn, Kanäle",
"Vivec, St. Delyn Glassworker's Hall":"Vivec, Hl.Delyn, Glashütte",
"Vivec, St. Delyn Underworks":"Vivec, Hl.Delyn, Unterirdische Kanäle",
"Vivec, St. Delyn Storage":"Vivec, Hl.Delyn, Lager",
"Vivec, St. Delyn Potter's Hall":"Vivec, Hl.Delyn, Töpferer-Halle",
"Vivec, St. Delyn Waist North-One":"Vivec, Hl.Delyn, Bodensektion Nord-Eins",
"Vivec, St. Delyn Waist South-Two":"Vivec, Hl.Delyn, Bodensektion Süd-Zwei",
"Vivec, St. Delyn Plaza":"Vivec, Hl.Deyln, Platz",
"Vivec, St. Delyn Waistworks":"Vivec, Hl.Delyn, Bodensektion",
"Vivec, St. Delyn Waist South-One":"Vivec, Hl.Delyn, Bodensektion Süd-Eins",
"Vivec, St. Delyn Waist North-Two":"Vivec, Hl.Delyn, Bodensektion Nord-Zwei",
"Vivec, St. Olms":"Vivec, Hl. Olms",
"Vivec, St. Olms Brewers and Fishmongers Hall":"Vivec, Hl.Olms, Brauer und Fischhändler-Halle",
"Vivec, St. Olms Canal North-One":"Vivec, Hl.Olms, Kanal Nord-Eins",
"Vivec, St. Olms Canal North-Three":"Vivec, Hl.Olms, Kanal Nord-Drei",
"Vivec, St. Olms Canal North-Two":"Vivec, Hl.Olms, Kanal Nord Zwei",
"Vivec, St. Olms Canal South-One":"Vivec, Hl.Olms, Kanal Süd-Eins",
"Vivec, St. Olms Canal South-Three":"Vivec, Hl.Olms, Kanal Süd-Drei",
"Vivec, St. Olms Canal South-Two":"Vivec, Hl.Olms, Kanal Süd-Zwei",
"Vivec, St. Olms Canalworks":"Vivec, Hl.Olms, Kanäle",
"Vivec, St. Olms Farmers and Laborers Hall":"Vivec, Hl.Olms, Bauern und Arbeiter-Halle",
"Vivec, St. Olms Haunted Manor":"Vivec, Hl.Olms, Spukhaus",
"Vivec, St. Olms Plaza":"Vivec, Hl.Olms, Platz",
"Vivec, St. Olms Storage":"Vivec, Hl.Olms, Lager",
"Vivec, St. Olms Tailors and Dyers Hall":"Vivec, Hl.Olms, Schneider und Färber-Halle",
"Vivec, St. Olms Tanners and Miners Hall":"Vivec, Hl.Olms, Gerber und Schürfer-Halle",
"Vivec, St. Olms Temple":"Vivec, Hl.Olms, Tempel",
"Vivec, St. Olms Underworks":"Vivec, Hl.Olms, Unterirdische Kanäle",
"Vivec, St. Olms Upper North-One":"Vivec, Hl.Olms, Obere Ebene Nord-Eins",
"Vivec, St. Olms Upper North-Two":"Vivec, Hl.Olms, Obere Ebene Nord-Zwei",
"Vivec, St. Olms Upper South-One":"Vivec, Hl.Olms, Obere Ebene Süd-Eins",
"Vivec, St. Olms Waist North-One":"Vivec, Hl.Olms, Bodensektion Nord-Eins",
"Vivec, St. Olms Waist North-Two":"Vivec, Hl.Olms, Bodensektion Nord-Zwei",
"Vivec, St. Olms Waist South-One":"Vivec, Hl.Olms, Bodensektion Süd-Eins",
"Vivec, St. Olms Waist South-Two":"Vivec, Hl.Olms, Bodensektion Süd-Zwei",
"Vivec, St. Olms Waistworks":"Vivec, Hl.Olms, Bodensektion",
"Vivec, St. Olms Yngling Manor":"Vivec, Hl.Olms, Haus Yngling",
"Vivec, St. Olms Yngling Manor Basement":"Vivec, Hl.Olms, Haus Yngling, Erdgeschoss",
"Vivec, Telvanni":"Vivec, Telvanni",
"Vivec, Telvanni Alchemist":"Vivec, Telvanni, Alchemist",
"Vivec, Telvanni Apothecary":"Vivec, Telvanni, Trankmischer",
"Vivec, Telvanni Canalworks":"Vivec, Telvanni, Kanäle",
"Vivec, Telvanni Enchanter":"Vivec, Telvanni, Verzauberungen",
"Vivec, Telvanni Mage":"Vivec, Telvanni, Magier",
"Vivec, Telvanni Monster Lab":"Vivec, Telvanni, Monster-Labor",
"Vivec, Telvanni Plaza":"Vivec, Telvanni, Platz",
"Vivec, Telvanni Prison Cells":"Vivec, Telvanni, Gefängniszellen",
"Vivec, Telvanni Sorcerer":"Vivec, Telvanni, Hexenmeister",
"Vivec, Telvanni Temple":"Vivec, Telvanni, Tempel",
"Vivec, Telvanni Tower":"Vivec, Telvanni, Turm",
"Vivec, Telvanni Underworks":"Vivec, Telvanni, Unterirdische Kanäle",
"Vivec, Telvanni Upper Storage":"Vivec, Telvanni, Oberes Lager",
"Vivec, Telvanni Vault":"Vivec, Telvanni, Gewölbe",
"Vivec, Telvanni Waistworks":"Vivec, Telvanni, Bodensektion",
"Vivec, Temple":"Vivec, Tempel",
"Vivec, Temporary Telvanni Housing":"Vivec, Telvanni-Notunterkünfte",
"Vivec, Tervur Braven: Trader":"Vivec, Tervur Braven: Händler",
"Vivec, The Abbey of St. Delyn the Wise":"Vivec, Die Abtei des Hl. Delyn des Weisen",
"Vivec, The Flowers of Gold":"Vivec, Taverne Goldblume",
"Vivec, The Lizard's Head":"Vivec, Der Echsenkopf",
"Vos":"Vos",
"Vos, Dreynos Elvul's Farmhouse":"Vos, Dreynos Elvuls Bauernhaus",
"Vos, Fanisea Irano's Farmhouse":"Vos, Fanisea Iranos Bauernhaus",
"Vos, Ienasa Radas's Farmhouse":"Vos, Ienasa Radas’ Bauernhaus",
"Vos, Maela Kaushad's Farmhouse":"Vos, Maela Kaushads Bauernhaus",
"Vos, Mandyn Ralas's Farmhouse":"Vos, Mandyn Ralas’ Bauernhaus",
"Vos, Menus Felas's Farmhouse":"Vos, Menus Felas’ Bauernhaus",
"Vos, Runethyne Andas's Farmhouse":"Vos, Runethyne Andas’ Bauernhaus",
"Vos, Thilse Aralas's Farmhouse":"Vos, Thilse Aralas’ Bauernhaus",
"Vos, Trilam Drolnor's Farmhouse":"Vos, Trilam Drolnors Bauernhaus",
"Vos, Ulvil Llothas's Farmhouse":"Vos, Ulvil Llothas’ Bauernhaus",
"Vos, Varo Tradehouse":"Vos, Varo-Handelshaus",
"Vos, Varo Tradehouse Entrance":"Vos, Varo-Handelshaus, Eingang",
"Vos, Varo Tradehouse Storage":"Vos, Varo-Handelshaus, Lager",
"Vos, Vos Chapel":"Vos, Kapelle",
"Wolverine Hall":"Wolfenhalle",
"Yakanalit":"Yakanalit",
"Yakaridan Camp, Kitbael's Yurt":"Yakaridan-Lager, Kitbaels Zelt",
"Yakin":"Yakin",
"Yakin, Shrine":"Yakin, Schrein",
"Yanemus Mine":"Yanemus, Mine",
"Yansirramus":"Yansirramus",
"Yansirramus, Shrine":"Yansirramus, Schrein",
"Yasammidan, Shrine":"Yasammidan, Schrein",
"Yasamsi":"Yasamsi",
"Yassu Mine":"Yassu Mine",
"Yesamsi":"Yesamsi",
"Zainab Camp":"Zainab-Lager",
"Zainab Camp, Ababael Timsar-Dadisun's Yurt":"Zainab Lager, Ababael Timsar-Dadisuns Zelt",
"Zainab Camp, Ashibaal's Yurt":"Zainab Lager, Ashibaals Zelt",
"Zainab Camp, Ashkhan's Yurt":"Zainab Lager, Zelt des Ashkhan",
"Zainab Camp, Ashur-Dan's Yurt":"Zainab Lager, Ashur-Dans Zelt",
"Zainab Camp, Kuda's Yurt":"Zainab Lager, Kudas Zelt",
"Zainab Camp, Kummu's Yurt":"Zainab Lager, Kummus Zelt",
"Zainab Camp, Minassour's Yurt":"Zainab Lager, Minassours Zelt",
"Zainab Camp, Patababi's Yurt":"Zainab Lager, Patababis Zelt",
"Zainab Camp, Tussi's Yurt":"Zainab Lager, Thusys Zelt",
"Zainab Camp, Wise Woman's Yurt":"Zainab Lager, Zelt der Weisen Frau",
"Zainsipilu":"Zainsipilu",
"Zaintirari":"Zaintirari",
"Zaintiraris":"Zaintiraris",
"Zaintiraris, Shrine":"Zaintiraris, Schrein",
"Zalkin Grotto":"Zalkin-Grotte",
"Zalkin-Sul Egg Mine":"Zalkin-Sul, Eiermine",
"Zanabi":"Zanabi",
"Zebabi":"Zebabi",
"Zenarbael":"Zenarbael",
"Zergonipal":"Zergonipa",
"Zergonipal, Shrine":"Zergonipal, Schrein",
"Bamz-Amschend, Hall of Wails":"Bamz-Amschend, Halle des Heulens",
"Bamz-Amschend, Hall of Winds":"Bamz-Amschend, Halle des Windes",
"Bamz-Amschend, Hearthfire Hall":"Bamz-Amschend, Halle des Herdfeuers",
"Bamz-Amschend, King's Walk":"Bamz-Amschend, Königsgang",
"Bamz-Amschend, Passage of the Walker":"Bamz-Amschend, Passage des Wandernden",
"Bamz-Amschend, Passage of Whispers":"Bamz-Amschend, Passage des Flüsterns",
"Bamz-Amschend, Radac's Forge":"Bamz-Amschend, Radacs Schmiede",
"Bamz-Amschend, Skybreak Gallery":"Bamz-Amschend, Himmelsspalt-Galerie",
"Mournhold":"Gramfeste",
"Mournhold Temple":"Gramfeste-Tempel",
"Mournhold Temple: Basement":"Gramfeste-Tempel: Keller",
"Mournhold Temple: Hall of Ministry":"Gramfeste-Tempel: Halle der Geistlichkeit",
"Mournhold Temple: High Chapel":"Gramfeste-Tempel: Hochkapelle",
"Mournhold Temple: Infirmary":"Gramfeste-Tempel: Krankenstube",
"Mournhold Temple: Office of the Lord Archcanon":"Gramfeste-Tempel: Büro des Erzkanonikers",
"Mournhold Temple: Reception Area":"Gramfeste-Tempel: Empfangsbereich",
"Mournhold, Andoren Manor":"Gramfeste, Haus Andoren",
"Mournhold, Armory":"Gramfeste, Waffenkammer",
"Mournhold, Bookseller":"Gramfeste, Buchhändler",
"Mournhold, Clothier":"Gramfeste, Schneider",
"Mournhold, Craftsmen's Hall":"Gramfeste, Halle der Handwerker",
"Mournhold, Geon Auline's House":"Gramfeste, Geon Aulines Haus",
"Mournhold, Godsreach":"Gramfeste, Göttergriff",
"Mournhold, Great Bazaar":"Gramfeste, Großer Basar",
"Mournhold, Ignatius Flaccus' House":"Gramfeste, Ignatius Flaccus' Haus",
"Mournhold, Llethan Manor":"Gramfeste, Haus Llethan",
"Mournhold, Magic Shop":"Gramfeste, Magieladen",
"Mournhold, Museum of Artifacts":"Gramfeste, Artefakt-Museum",
"Mournhold, Pawnbroker":"Gramfeste, Pfandleiher",
"Mournhold, Plaza Brindisi Dorom":"Gramfeste, Brindisi-Dorom-Platz",
"Mournhold, Royal Palace":"Gramfeste, Königspalast",
"Mournhold, Royal Palace Throne Room":"Gramfeste, Thronraum des Königspalasts",
"Mournhold, Royal Palace: Barenziah's Chambers":"Gramfeste, Königspalast: Barenziahs Gemächer",
"Mournhold, Royal Palace: Basement":"Gramfeste, Königspalast: Keller",
"Mournhold, Royal Palace: Courtyard":"Gramfeste, Königspalast: Hof",
"Mournhold, Royal Palace: Guards' Quarters":"Gramfeste, Königspalast: Quartiere der Wachen",
"Mournhold, Royal Palace: Helseth's Chambers":"Gramfeste, Königspalast: Helseths Gemächer",
"Mournhold, Royal Palace: Imperial Cult Services":"Gramfeste, Königspalast: Dienste des Kaiserlichen Kults",
"Mournhold, Royal Palace: Jail":"Gramfeste, Königspalast: Kerker",
"Mournhold, Royal Palace: Legion Depot":"Gramfeste, Königspalast: Legionsdepot",
"Mournhold, Royal Palace: Reception Area":"Gramfeste, Königspalast: Empfangsbereich",
"Mournhold, Sadri Manor":"Gramfeste, Haus Sadri",
"Mournhold, Secret Office":"Gramfeste, Geheime Schreibstube",
"Mournhold, Temple Courtyard":"Gramfeste, Tempelhof",
"Mournhold, The Winged Guar":"Gramfeste, Der geflügelte Guar",
"Mournhold, Thendas Manor":"Gramfeste, Haus Thendas",
"Mournhold, Trader":"Gramfeste, Händler",
"Mournhold, Vacant Manor":"Gramfeste, leeres Haus",
"Mournhold, Velas Manor":"Gramfeste, Haus Velas",
"Norenen-dur":"Norenen-dur",
"Norenen-dur, Basilica of Divine Whispers":"Norenen-dur, Basilika des göttlichen Flüsterns",
"Norenen-dur, Citadel of Myn Dhrur":"Norenen-dur, Zitadelle von Myn Dhrur",
"Norenen-dur, The Grand Stair":"Norenen-dur, Die große Treppe",
"Norenen-dur, The Teeth that Gnash":"Norenen-dur, Die knirschenden Zähne",
"Norenen-dur, The Wailingdelve":"Norenen-dur, Der Jammergraben",
"Old Mournhold: Abandoned Crypt":"Alt-Gramfeste: Verlassene Gruft",
"Old Mournhold: Abandoned Passageway":"Alt-Gramfeste: Verlassener Gang",
"Old Mournhold: Armory Ruins":"Alt-Gramfeste: Gramfeste, Waffenkammer-Ruinen",
"Old Mournhold: Battlefield":"Alt-Gramfeste: Schlachtfeld",
"Old Mournhold: Bazaar Sewers":"Alt-Gramfeste: Basar-Abwasserkanäle",
"Old Mournhold: City Gate":"Alt-Gramfeste: Stadttor",
"Old Mournhold: Forgotten Sewer":"Alt-Gramfeste: Verlassene Kanäle",
"Old Mournhold: Gedna Relvel's Tomb":"Alt-Gramfeste: Gedna Relvels Grab",
"Old Mournhold: Manor District":"Alt-Gramfeste: Häuser-Distrikt",
"Old Mournhold: Moril Manor, Courtyard":"Alt-Gramfeste: Haus Moril, Hof",
"Old Mournhold: Moril Manor, East Building":"Alt-Gramfeste: Haus Moril, Ostgebäude",
"Old Mournhold: Moril Manor, North Building":"Alt-Gramfeste: Haus Moril, Nordgebäude",
"Old Mournhold: Palace Sewers":"Alt-Gramfeste: Palastkanäle",
"Old Mournhold: Residential Ruins":"Alt-Gramfeste: Häuserruinen",
"Old Mournhold: Residential Sewers":"Alt-Gramfeste: Häuser-Abwasserkanäle",
"Old Mournhold: Tears of Amun-Shae":"Alt-Gramfeste: Tränen von Amun-Shae",
"Old Mournhold: Temple Catacombs":"Alt-Gramfeste: Tempelkatakomben",
"Old Mournhold: Temple Crypt":"Alt-Gramfeste: Tempelgruft",
"Old Mournhold: Temple Gardens":"Alt-Gramfeste: Tempelgärten",
"Old Mournhold: Temple Sewers":"Alt-Gramfeste: Tempelkanäle",
"Old Mournhold: Temple Sewers East":"Alt-Gramfeste: Tempelkanäle Ost",
"Old Mournhold: Temple Sewers West":"Alt-Gramfeste: Tempelkanäle West",
"Old Mournhold: Temple Shrine":"Alt-Gramfeste: Tempelschrein",
"Old Mournhold: Teran Hall":"Alt-Gramfeste: Teran-Halle",
"Old Mournhold: Teran Hall, East Bldg":"Alt-Gramfeste: Teran-Halle, Ostgebäude",
"Old Mournhold: West Sewers":"Alt-Gramfeste: West-Kanäle",
"Pelagiad, Ignatius Flaccus' House":"Pelagiad, Ignatius Flaccus' House",
"Sotha Sil,":"Sotha Sil",
"Sotha Sil, Central Gearworks":"Sotha Sil, Zentrale Mechanik",
"Sotha Sil, Chamber of Sohleh":"Sotha Sil, Kammer von Sohleh",
"Sotha Sil, Dome of Kasia":"Sotha Sil, Kuppel von Kasia",
"Sotha Sil, Dome of Serlyn":"Sotha Sil, Kuppel von Serlyn",
"Sotha Sil, Dome of Sotha Sil":"Sotha Sil, Kuppel von Sotha Sil",
"Sotha Sil, Dome of the Imperfect":"Sotha Sil, Kuppel der Unfertigen",
"Sotha Sil, Dome of Udok":"Sotha Sil, Kuppel von Udok",
"Sotha Sil, Hall of Delirium":"Sotha Sil, Halle des Deliriums",
"Sotha Sil, Hall of Mileitho":"Sotha Sil, Halle von Mileitho",
"Sotha Sil, Hall of Sallaemu":"Sotha Sil, Halle von Sallaemu",
"Sotha Sil, Hall of Theuda":"Sotha Sil, Halle von Theuda",
"Sotha Sil, Inner Flooded Halls":"Sotha Sil, Innere überflutete Hallen",
"Sotha Sil, Outer Flooded Halls":"Sotha Sil, Äußere überflutete Hallen",
"Solstheim, Gyldenhul Barrow Entrance":"Solstheim, Eingang Gyldenhul-Hügelgrab",
"Solstheim, Altar of Thrond":"Solstheim, Altar von Thrond",
"Solstheim, Brodir Grove":"Solstheim, Brodir-Hain",
"Solstheim, Castle Karstaag":"Solstheim, Burg Karstaag",
"Solstheim, Hrothmund's Bane":"Solstheim, Hrothmunds Fluch",
"Solstheim, Mortrag Glacier":"Solstheim, Mortrag-Gletscher",
"Solstheim, Hvitkald Peak":"Solstheim, Hvitkald-Gipfel",
"Solstheim, Thormoor's Watch":"Solstheim, Thormoors Wacht",
"Solstheim, Lake Fjalding":"Solstheim, Fjalding-See",
"Thirsk":"Thirsk",
"Skaal Village":"Skaal-Dorf",
"Fort Frostmoth":"Eisfalter-Festung",
"Raven Rock":"Rabenfels",
"Draugr Test":"Draugr Test",
"Fort Frostmoth, Armory":"Eisfalter-Festung, Waffenkammer",
"Fort Frostmoth, Carius' Chambers":"Eisfalter-Festung, Carius' Kammern",
"Fort Frostmoth, Curtain Wall":"Eisfalter-Festung, Zwischenwand",
"Fort Frostmoth, General Quarters":"Eisfalter-Festung, Quartiere",
"Fort Frostmoth, General Quarters, Upper Level":"Eisfalter-Festung, Quartiere, obere Etage",
"Fort Frostmoth, Imperial Cult Shrine":"Eisfalter-Festung, Schrein des Kaiserlichen Kults",
"Fort Frostmoth, Prison":"Eisfalter-Festung, Kerker",
"Fort Frostmoth, Supply Room":"Eisfalter-Festung, Vorratskammer",
"Mark's Script Testing Cell":"Mark's Script Testing Cell",
"Raven Rock, Abandoned Mine Shaft":"Rabenfels, Verlassener Minenschacht",
"Raven Rock, Afer Flaccus' House":"Rabenfels, Afer Flaccus' Haus",
"Raven Rock, Bar":"Rabenfels, Taverne",
"Raven Rock, Factor's Estate":"Rabenfels, Anwesen des Verwalters",
"Raven Rock, Garnas Uvalen's House":"Rabenfels, Garnas Uvalens Haus",
"Raven Rock, Gidar Verothan's House":"Rabenfels, Gidar Verothans Haus",
"Raven Rock, Gratian Caerellius' House":"Rabenfels, Gratian Caerellius' Haus",
"Raven Rock, Mine":"Rabenfels, Mine",
"Raven Rock, Mine Entrance":"Rabenfels, Mineneingang",
"Raven Rock, North Storehouse":"Rabenfels, Nördliches Lager",
"Raven Rock, Sabinus Oranius' House":"Rabenfels, Sabinus Oranius' Haus",
"Raven Rock, Sados Relothan's House":"Rabenfels, Sados Relothans Haus",
"Raven Rock, Seler Favelnim's House":"Rabenfels, Seler Favelnims Haus",
"Raven Rock, Smith":"Rabenfels, Schmied",
"Raven Rock, South Storehouse":"Rabenfels, Südliches Lager",
"Raven Rock, SouthEast Storehouse":"Rabenfels, Südöstliches Lager",
"Raven Rock, Supply Ship":"Rabenfels, Versorgungsschiff",
"Raven Rock, Trader":"Rabenfels, Händler",
"Raven Rock, Uryn Maren's House":"Rabenfels, Uryn Marens Haus",
"Raven Rock, Vacant House":"Rabenfels, Leeres Haus",
"Skaal Village, Bronrod the Roarer's House":"Skaal-Dorf, Haus von Bronrod dem Brüllenden",
"Skaal Village, Erna the Quiet's House":"Skaal-Dorf, Haus von Erna der Ruhigen",
"Skaal Village, Ice-Mane's Hut":"Skaal-Dorf, Eismähnes Hut",
"Skaal Village, Ingmar's House":"Skaal-Dorf, Ingmars Haus",
"Skaal Village, Lassnr's House":"Skaal-Dorf, Lassnrs Haus",
"Skaal Village, Rigmor's Hut":"Skaal-Dorf, Rigmors Hütte",
"Skaal Village, Shaman's Hut":"Skaal-Dorf, Schamanenhütte",
"Skaal village, Snedbrir the Smith":"Skaal-Dorf, Snedbrir der Schmied",
"Skaal Village, The Blodskaal's House":"Skaal-Dorf, Blodskaals Haus",
"Skaal Village, The Greathall":"Skaal-Dorf, Die Große Halle",
"Solstheim":"Solstheim",
"Solstheim, Aesliip's Lair":"Solstheim, Aesliips Höhle",
"Solstheim, Aesliip's Lair, Caverns":"Solstheim, Aesliips Höhle, Gewölbe",
"Solstheim, Benkongerike":"Solstheim, Benkongerike",
"Solstheim, Bjorn":"Solstheim, Bjorn",
"Solstheim, Bloodskal Barrow":"Solstheim, Blutskal-Hügelgrab",
"Solstheim, Castle Karstaag, Banquet Hall":"Solstheim, Burg Karstaag, Bankettsaal",
"Solstheim, Castle Karstaag, Caverns of Karstaag":"Solstheim, Burg Karstaag, Gewölbe",
"Solstheim, Castle Karstaag, Karstaag's Chambers":"Solstheim, Burg Karstaag, Karstaags Kammern",
"Solstheim, Castle Karstaag, Throne Room":"Solstheim, Burg Karstaag, Thronsaal",
"Solstheim, Castle Karstaag, Tower":"Solstheim, Burg Karstaag, Turm",
"Solstheim, Cave of Hidden Music":"Solstheim, Höhle der verborgenen Melodie",
"Solstheim, Caves of Fjalding":"Solstheim, Fjalding-Höhlen",
"Solstheim, Chamber of Song":"Solstheim, Kammer des Lieds",
"Solstheim, Connorflenge Barrow":"Solstheim, Connorflenge-Hügelgrab",
"Solstheim, Domme":"Solstheim, Domme",
"Solstheim, Eddard Barrow":"Solstheim, Eddard-Hügelgrab",
"Solstheim, Fjell":"Solstheim, Fjell",
"Solstheim, Frossel":"Solstheim, Frossel",
"Solstheim, Frosselmane Barrow":"Solstheim, Frosselmane-Hügelgrab",
"Solstheim, Frykte":"Solstheim, Frykte",
"Solstheim, Gandrung Caverns":"Solstheim, Gandrung-Höhlen",
"Solstheim, Geilir the Mumbling's Dwelling":"Solstheim, Behausung von Geilir dem Murmler",
"Solstheim, Glenschul's Tomb":"Solstheim, Glenschuls Grab",
"Solstheim, Gloomy Cave":"Solstheim, Düstere Höhle",
"Solstheim, Graring's House":"Solstheim, Grarings Haus",
"Solstheim, Gronn":"Solstheim, Gronn",
"Solstheim, Gyldenhul Barrow":"Solstheim, Gyldenhul-Hügelgrab",
"Solstheim, Halls of Penumbra":"Solstheim, Penumbra-Hallen",
"Solstheim, Himmelhost Barrow":"Solstheim, Himmelhost-Hügelgrab",
"Solstheim, Hrothmund's Barrow":"Solstheim, Hrothmunds Hügelgrab",
"Solstheim, Jolgeirr Barrow":"Solstheim, Jolgeirr-Hügelgrab",
"Solstheim, Kelsedolk Barrow":"Solstheim, Kelsedolk-Hügelgrab",
"Solstheim, Kjolver's Dwelling":"Solstheim, Kjolvers Behausung",
"Solstheim, Kolbjorn Barrow":"Solstheim, Kolbjorn-Hügelgrab",
"Solstheim, Kolfinna's Dwelling":"Solstheim, Kolfinnas Behausung",
"Solstheim, Lair of the Udyrfrykte":"Solstheim, Höhle des Udyrfrykte",
"Solstheim, Legge":"Solstheim, Legge",
"Solstheim, Lukesturm Barrow":"Solstheim, Lukesturm-Hügelgrab",
"Solstheim, Mortrag Glacier: Entry":"Solstheim, Mortrag-Gletscher: Eingang",
"Solstheim, Mortrag Glacier: Huntsman's Hall":"Solstheim, Mortrag-Gletscher: Jagdmann-Hallen",
"Solstheim, Mortrag Glacier: Inner Ring":"Solstheim, Mortrag-Gletscher: Innerer Ring",
"Solstheim, Mortrag Glacier: Outer Ring":"Solstheim, Mortrag-Gletscher: Äußerer Ring",
"Solstheim, Rimhull":"Solstheim, Rimhull",
"Solstheim, Sjobal":"Solstheim, Sjobal",
"Solstheim, Skogsdrake Barrow":"Solstheim, Skogsdrake-Hügelgrab",
"Solstheim, Skygge":"Solstheim, Skygge",
"Solstheim, Solvjord":"Solstheim, Solvjord",
"Solstheim, Stahlman's Gorge":"Solstheim, Stahlman-Schlucht",
"Solstheim, Stormpfund Barrow":"Solstheim, Stormpfund-Hügelgrab",
"Solstheim, Thirsk":"Solstheim, Thirsk",
"Solstheim, Tombs of Skaalara":"Solstheim, Gruft von Skaalara",
"Solstheim, Ulfgar the Unending's Dwelling":"Solstheim, Ulfgars des Endlosen Behausung",
"Solstheim, Uncle Sweetshare's Workshop":"Solstheim, Onkel Leckermauls Werkstatt",
"Solstheim, Valbrandr Barrow":"Solstheim, Valbrandr-Hügelgrab",
"Solstheim, Varstaad Caves":"Solstheim, Varstaad-Höhlen",
"Vor Lair, Chambers of Alta Vor":"Vor Lair, Chambers of Alta Vor",
"Vor Lair, Interior":"Vor Lair, Interior"}


from pathlib import Path
import re

def replace(path):
    print(path)
    with open(path) as f:
	    s = f.read()
    for key in Celldata.keys():
        insensitive_replace = re.compile(re.escape("\""+key+"\""), re.IGNORECASE|re.MULTILINE)
        t = insensitive_replace.search(s);
        if t is not None:
            print(path.__str__() + " >> " + t.__str__())
        s = insensitive_replace.sub("\""+Celldata[key]+"\"", s)
    with open(path, "w") as f:
        f.write(s)

for path in Path('.').rglob('*.lua'):
    replace(path)
for path in Path('.').rglob('*.json'):
    replace(path)